const React = require('react')
const { createElement: h, useEffect, useState, useSyncExternalStore } = React
const { IconCheckOutline16, IconChecklistOutline14, IconCloseOutline16, IconRefreshOutline16, Tooltip } = require('@deepseek-ai/dsh-client-ui-primitives')
const NS = 'dofe.yootun-approvals'; const PATH = '/api/desktop/yootun/approvals'
const OVERLAY_ID = '@dofe/dsh-yootun-approvals'
const OVERLAY_EVENT = 'dofe:yootun-overlay:open'
const DIALOG_ATTRIBUTES = { role: 'dialog', 'aria-modal': true, 'aria-labelledby': 'ya-title' }
const copy = { zh: { open: '统一审批', title: '统一审批与审计', subtitle: '高风险动作的人工确认队列', close: '关闭统一审批', refresh: '刷新', pending: '待确认', confirmed: '已确认', dismissed: '已撤销', succeeded: '适配器已完成', failed: '适配器执行失败', requiresLogin: '需要重新登录', actions: '动作队列', empty: '暂无待确认动作', approve: '确认', dismiss: '撤销', source: '来源', risk: '风险' }, en: { open: 'Approvals', title: 'Approvals & audit', subtitle: 'Human confirmation for high-risk actions', close: 'Close approvals', refresh: 'Refresh', pending: 'Awaiting approval', confirmed: 'Approved', dismissed: 'Dismissed', succeeded: 'Adapter completed', failed: 'Adapter failed', requiresLogin: 'Login required', actions: 'Action queue', empty: 'No pending actions', approve: 'Approve', dismiss: 'Dismiss', source: 'Source', risk: 'Risk' } }
let opened = false; const listeners = new Set(); const emit = () => listeners.forEach(listener => listener()); const setOpened = value => { opened = value; emit() }; const subscribe = listener => { listeners.add(listener); return () => listeners.delete(listener) }; const snapshot = () => opened
const openOverlay = () => { window.dispatchEvent(new CustomEvent(OVERLAY_EVENT, { detail: { id: OVERLAY_ID } })); setOpened(true); requestAnimationFrame(() => { const root = document.querySelector('.ya-overlay'); for (const [name, value] of Object.entries(DIALOG_ATTRIBUTES)) root?.setAttribute(name, String(value)) }) }
const closeOtherOverlay = event => { if (event.detail?.id !== OVERLAY_ID) setOpened(false) }
async function load(signal) { const response = await fetch(PATH, { credentials: 'same-origin', signal, headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('approval request failed'); return response.json() }
async function mutate(body) { const response = await fetch(PATH, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error('approval mutation failed'); return response.json() }
function Metric({ label, value }) { return h('div', { className: 'ya-metric' }, h('span', null, label), h('strong', null, String(value ?? 0))) }
function statusText(status, t) { return status === 'awaiting_confirmation' ? t('pending') : status === 'confirmed_pending_adapter' ? t('confirmed') : status === 'succeeded' ? t('succeeded') : status === 'failed' ? t('failed') : status === 'requires_user_login' ? t('requiresLogin') : t('dismissed') }
function Item({ item, t, update }) { return h('article', { className: 'ya-item', 'data-status': item.status }, h('div', { className: 'ya-item-main' }, h('strong', null, item.targetLabel), h('span', null, item.summary), h('small', null, `${t('source')}: ${item.source} · ${t('risk')}: ${item.risk} · ${statusText(item.status, t)}`)), item.status === 'awaiting_confirmation' ? h('div', { className: 'ya-buttons' }, h('button', { type: 'button', onClick: () => update({ action: 'confirm', id: item.id }) }, h(IconCheckOutline16, { size: 14 }), t('approve')), h('button', { type: 'button', onClick: () => update({ action: 'dismiss', id: item.id }) }, h(IconCloseOutline16, { size: 14 }), t('dismiss'))) : null) }
function Overlay({ t }) { const visible = useSyncExternalStore(subscribe, snapshot, snapshot); const [data, setData] = useState(null); const [error, setError] = useState(false); const [revision, setRevision] = useState(0); useEffect(() => { if (!visible) return undefined; const controller = new AbortController(); setError(false); void load(controller.signal).then(setData).catch(cause => { if (cause?.name !== 'AbortError') setError(true) }); return () => controller.abort() }, [visible, revision]); useEffect(() => { if (!visible) return undefined; const key = event => { if (event.key === 'Escape') setOpened(false) }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [visible]); if (!visible) return null; const current = data || { dashboard: {}, actions: [] }; const update = async body => { try { setData(await mutate(body)) } catch { setError(true) } }; const content = error && !data ? h('div', { role: 'alert', className: 'ya-empty' }, 'Unable to load approvals') : h(React.Fragment, null, h('div', { className: 'ya-metrics' }, h(Metric, { label: t('pending'), value: current.dashboard.pending }), h(Metric, { label: t('confirmed'), value: current.dashboard.confirmed }), h(Metric, { label: t('dismissed'), value: current.dashboard.dismissed })), h('section', { className: 'ya-section' }, h('h2', null, t('actions')), (current.actions || []).length ? current.actions.map(item => h(Item, { key: item.id, item, t, update })) : h('div', { className: 'ya-empty' }, t('empty')))); return h('div', { className: 'ya-overlay' }, h('main', { className: 'ya-shell', 'aria-labelledby': 'ya-title' }, h('header', { className: 'ya-header' }, h('div', null, h('h1', { id: 'ya-title' }, t('title')), h('p', null, t('subtitle'))), h('div', { className: 'ya-header-buttons' }, h(Tooltip, { label: t('refresh') }, h('button', { type: 'button', 'aria-label': t('refresh'), onClick: () => setRevision(value => value + 1) }, h(IconRefreshOutline16, { size: 16 }))), h(Tooltip, { label: t('close') }, h('button', { type: 'button', 'aria-label': t('close'), onClick: () => setOpened(false) }, h(IconCloseOutline16, { size: 16 }))))), h('div', { className: 'ya-content' }, content))) }
function Button({ wide, t }) { return h(Tooltip, { label: t('open'), disabled: wide }, h('button', { type: 'button', className: `ya-button${wide ? ' ya-wide' : ''}`, 'aria-label': t('open'), onClick: openOverlay }, h(IconChecklistOutline14, { size: wide ? 14 : 18 }), wide ? h('span', null, t('open')) : null)) }
const css = `.ya-button{display:flex;width:36px;height:36px;align-items:center;justify-content:center;gap:8px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.ya-button:hover{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}.ya-wide{width:100%;height:34px;justify-content:flex-start;padding:0 10px}.ya-wide span{font-size:13px}.ya-overlay{position:fixed;inset:0;z-index:510;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary)}.ya-shell{display:grid;grid-template-rows:auto 1fr;width:100%;height:100%;overflow:hidden}.ya-header{display:flex;min-height:74px;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid var(--dsw-alias-border-l1)}.ya-header h1{margin:0;font-size:20px}.ya-header p{margin:4px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px}.ya-header-buttons{display:flex;gap:6px}.ya-header-buttons button{display:grid;width:34px;height:34px;place-items:center;border:1px solid var(--dsw-alias-border-l1);border-radius:6px;background:var(--dsw-alias-bg-layer-1);color:inherit;cursor:pointer}.ya-content{overflow:auto;padding:22px 24px 40px}.ya-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));max-width:1120px;margin:0 auto;border-block:1px solid var(--dsw-alias-border-l1)}.ya-metric{display:grid;min-height:82px;align-content:center;gap:6px;padding:12px 16px;border-right:1px solid var(--dsw-alias-border-l1)}.ya-metric:last-child{border-right:0}.ya-metric span,.ya-item span,.ya-item small{color:var(--dsw-alias-label-secondary);font-size:12px}.ya-metric strong{font-size:24px}.ya-section{display:grid;gap:10px;max-width:1120px;margin:24px auto 0}.ya-section h2{margin:0;font-size:14px}.ya-item{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:14px 16px;border-top:1px solid var(--dsw-alias-border-l1)}.ya-item-main{display:grid;gap:5px;min-width:0}.ya-item-main strong,.ya-item-main span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ya-buttons{display:flex;gap:6px;flex:none}.ya-buttons button{display:inline-flex;align-items:center;gap:6px;min-height:32px;padding:0 10px;border:1px solid var(--dsw-alias-border-l1);border-radius:6px;background:var(--dsw-alias-bg-layer-1);color:inherit;font:inherit;cursor:pointer}.ya-empty{display:grid;min-height:150px;place-items:center;color:var(--dsw-alias-label-secondary);font-size:13px;text-align:center}@media(max-width:800px){.ya-header,.ya-content{padding-left:16px;padding-right:16px}.ya-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.ya-metric{padding:10px}.ya-item{align-items:flex-start;flex-direction:column}.ya-buttons{width:100%}.ya-buttons button{flex:1;justify-content:center}}`
function apply(ctx) { ctx.effect(() => ctx.locale.register(NS, copy), 'dofe-yootun-approvals: dictionaries'); ctx.effect(() => { window.addEventListener(OVERLAY_EVENT, closeOtherOverlay); return () => window.removeEventListener(OVERLAY_EVENT, closeOtherOverlay) }, 'dofe-yootun-approvals: exclusive-overlay'); ctx.effect(() => { const style = document.createElement('style'); style.dataset.plugin = '@dofe/dsh-yootun-approvals'; style.textContent = css; document.head.appendChild(style); return () => style.remove() }, 'dofe-yootun-approvals: styles'); ctx.effect(() => { window.addEventListener('dofe:yootun-approvals:open', openOverlay); return () => window.removeEventListener('dofe:yootun-approvals:open', openOverlay) }, 'dofe-yootun-approvals: open-event'); const t = ctx.locale.bind(NS); ctx.slots.inject('sidebar.footer.action', () => ctx.slots.register({ name: 'sidebar.footer.action', id: 'dofe-yootun-approvals', order: 50, inject: () => ({ t }) }, Button)); ctx.slots.inject('shell.overlay', () => ctx.slots.register({ name: 'shell.overlay', id: 'dofe-yootun-approvals', order: 50, inject: () => ({ t }) }, Overlay)) }
module.exports = { apply, inject: ['slots', 'locale'] }
