import { mkdtemp, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { describe, expect, it } from 'vitest'
import { handleYootunApprovalsRequest, YOOTUN_APPROVALS_PATH } from '../src/yootun-approvals-route.ts'
function request(method: string, body?: string): any { const chunks = body === undefined ? [] : [Buffer.from(body)]; return { method, headers: { origin: 'http://127.0.0.1:43120' }, socket: { remoteAddress: '127.0.0.1' }, async *[Symbol.asyncIterator]() { yield* chunks } } }
function response() { let raw = ''; return { statusCode: 0, setHeader() {}, end(value = '') { raw += value }, get status() { return this.statusCode }, body() { return raw ? JSON.parse(raw) : undefined } } as any }
describe('Yootun approvals route', () => { it('queues, confirms, and audits a high-risk action', async () => { const root = await mkdtemp(join(tmpdir(), 'yootun-approvals-')); const statePath = join(root, 'state.json'); const queued = response(); await handleYootunApprovalsRequest(request('POST', JSON.stringify({ action: 'enqueue', source: 'recruiter', targetLabel: '候选人消息', summary: '发送面试邀约草稿', risk: 'high' })), queued, 'http://127.0.0.1:43120', { statePath }); expect(queued.body().dashboard.pending).toBe(1); const confirmed = response(); await handleYootunApprovalsRequest(request('POST', JSON.stringify({ action: 'confirm', id: queued.body().actions[0].id })), confirmed, 'http://127.0.0.1:43120', { statePath }); expect(confirmed.body().dashboard.confirmed).toBe(1); expect(JSON.parse(await readFile(statePath, 'utf8')).actions[0].status).toBe('confirmed_pending_adapter') })
  it('rejects unknown fields and degrades corrupt state', async () => { const root = await mkdtemp(join(tmpdir(), 'yootun-approvals-corrupt-')); const statePath = join(root, 'state.json'); await import('node:fs/promises').then(fs => fs.writeFile(statePath, '{broken')); const result = response(); await handleYootunApprovalsRequest(request('POST', JSON.stringify({ action: 'enqueue', source: 'x', targetLabel: 'y', summary: 'z', risk: 'high', secret: 'no' })), result, 'http://127.0.0.1:43120', { statePath }); expect(result.status).toBe(400); const get = response(); await handleYootunApprovalsRequest(request('GET'), get, 'http://127.0.0.1:43120', { statePath }); expect(get.body()).toMatchObject({ dashboard: { pending: 0 }, actions: [] }); expect(YOOTUN_APPROVALS_PATH).toBe('/api/desktop/yootun/approvals') }) })
