import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
const root = new URL('../', import.meta.url)
test('publishes the web operation audit plugin with a bundle patch', async () => { const manifest = JSON.parse(await readFile(new URL('package.json', root), 'utf8')); assert.equal(manifest.name, '@dofe/dsh-yootun-audit'); assert.equal(manifest.description, 'Yootun operation audit workspace'); assert.equal(manifest.dsh.client.platform, 'web'); assert.equal(manifest.dsh.bundle.patch, './cordis.patch.yml') })
test('is a read-only audit workspace with no central approval actions', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /操作审计/u); assert.match(source, /\/api\/desktop\/yootun\/audit/u); assert.doesNotMatch(source, /统一审批|批准操作|拒绝操作|awaiting_confirmation|dofe:yootun-approvals|\/yootun\/approvals/u); assert.doesNotMatch(source, /password|cookie|银行卡|聊天正文/iu) })
test('marks each local pending event in the list and detail', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /pendingItem/u); assert.match(source, /event\.syncStatus === 'pending'/u) })
test('names the team search control for assistive technology', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /value: state\.teamQuery,[\s\S]*'aria-label': t\('searchTeam'\)/u) })
test('does not clear team search results when an obsolete request is cancelled', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /query\.toString\(\), controller\.signal\)[\s\S]*catch\(error => \{ if \(error\?\.name !== 'AbortError'\) dispatch\(\{ type: 'teams', value: \[\] \}\) \}\)/u) })
test('uses only DSH alpha3 exported icons', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); const imports = source.match(/const \{([^}]+)\} = require\('@deepseek-ai\/dsh-client-ui-primitives'\)/u)?.[1] || ''; const exported = await readFile(new URL('../../../deepseek-harness/packages/client/ui-primitives/src/icons/index.tsx', root), 'utf8'); for (const name of imports.split(',').map(token => token.trim()).filter(token => token.startsWith('Icon'))) assert.match(exported, new RegExp(`export const ${name}\\b`, 'u')) })
test('keeps keyboard focus visible across audit controls', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /focus-visible/u); assert.match(source, /ya-row:focus-visible/u); assert.match(source, /ya-filters input:focus-visible/u) })
test('exposes the selectable audit log with listbox semantics', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /role: 'listbox'/u); assert.match(source, /role: 'option'/u); assert.match(source, /'aria-selected': selectedId === event\.id/u) })
test('prevents duplicate and stale retry or pagination requests', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); for (const token of ['retryBusyRef.current', 'appendBusyRef.current', 'queryRevisionRef.current', 'const requestRevision = ++queryRevisionRef.current', 'const requestRevision = queryRevisionRef.current', 'if (queryRevisionRef.current === requestRevision)', "disabled: retrying", "retrying ? t('loading') : t('retry')", "'aria-busy': state.loading || state.appending || state.retrying"]) assert.ok(source.includes(token), `missing request guard token: ${token}`) })
test('cancels obsolete pagination when the audit query changes', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); for (const token of ['appendControllerRef.current?.abort()', 'appendControllerRef.current = controller', 'controller.signal', "error?.name !== 'AbortError'", 'appendControllerRef.current === controller']) assert.ok(source.includes(token), `missing pagination cancellation token: ${token}`) })
