import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import { ApiResponseSchema, PaginatedResponseSchema } from '../base';
import {
  AgentOnboardingStatusSchema,
  CreateDocumentSchema,
  UploadKnowledgeDocumentSchema,
  CreateMemorySchema,
  ExternalFileIngestResultSchema,
  IngestExternalFileSchema,
  DocumentPrincipalSchema,
  DocumentPrincipalListQuerySchema,
  GrantDocumentPrincipalSchema,
  RevokeDocumentPrincipalSchema,
  GrantKnowledgeAclSchema,
  KnowledgeAclGrantSchema,
  KnowledgeAclListQuerySchema,
  RevokeKnowledgeAclSchema,
  KnowledgePrincipalListQuerySchema,
  KnowledgePrincipalSchema,
  UpdateKnowledgePrincipalStatusSchema,
  GrantApiKeyBindingSchema,
  KnowledgeApiKeyBindingSchema,
  KnowledgeApiKeyListQuerySchema,
  RevokeApiKeyBindingSchema,
  KnowledgePolicySchema,
  UpdateKnowledgePolicySchema,
  KnowledgePolicyApprovalSchema,
  KnowledgePolicyApprovalListQuerySchema,
  DecideKnowledgePolicyApprovalSchema,
  MemoryExportQuerySchema,
  MemoryExportResultSchema,
  CreateMemoryStrategySchema,
  EnqueueMemoryStrategyReplaySchema,
  CreateMemoryReplayPlanSchema,
  MemoryReplayPlanSchema,
  RequestMemoryStrategyBaselineSchema,
  ReportMemoryStrategyBaselineSchema,
  CreateSourceSchema,
  CreateSpaceSchema,
  DashboardOverviewSchema,
  KnowledgeTenantSummarySchema,
  KnowledgeTenantListQuerySchema,
  KnowledgeDocumentSchema,
  KnowledgeConnectorCredentialSchema,
  KnowledgeDocumentListQuerySchema,
  KnowledgeGraphQuerySchema,
  KnowledgeGraphSchema,
  KnowledgeListQuerySchema,
  KnowledgeSearchResponseSchema,
  KnowledgeSearchSchema,
  KnowledgeSourceSchema,
  CheckKnowledgeSourceResultSchema,
  KnowledgeSourceListQuerySchema,
  KnowledgeSpaceSchema,
  MemorySchema,
  MemoryListQuerySchema,
  MemoryStrategyListQuerySchema,
  MemoryStrategySchema,
  MemoryStrategyExecutionContextSchema,
  MemoryStrategyGuardResultSchema,
  ReportMemoryStrategyTrialSchema,
  RebuildKnowledgeGraphResultSchema,
  RebuildKnowledgeGraphSchema,
  SessionCheckpointSchema,
  ScoreMemorySchema,
  UpdateMemoryStatusSchema,
  DeleteIntegrationObjectResultSchema,
  ExternalGraphSnapshotReferenceSchema,
  ExternalGraphSnapshotSchema,
  IntegrationObjectMetadataSchema,
  IntegrationObjectReferenceSchema,
  IntegrationObjectSchema,
  PutExternalGraphSnapshotSchema,
  PutIntegrationObjectSchema,
  RecallTraceDetailSchema,
  RecallTraceListQuerySchema,
  RecallTraceSchema,
  SessionFinalizeSchema,
  SessionContinuationSchema,
  SessionContinuationResponseSchema,
  SessionHandoffSchema,
  SessionHandoffListQuerySchema,
  SessionHandoffAcceptResultSchema,
  SessionHandoffCancelResultSchema,
  HandoffAcceptSchema,
  HandoffCancelSchema,
  RecordMemoryFeedbackSchema,
  MemoryFeedbackSchema,
  MemoryFeedbackListQuerySchema,
  MemoryFeedbackAggregateSchema,
  MemoryConflictSchema,
  MemoryConflictListQuerySchema,
  ResolveMemoryConflictSchema,
  McpEntityMergeQuerySchema,
  KnowledgeEntityMergeSchema,
  DecideEntityMergeSchema,
  ProposeEntityMergeContractSchema,
  MemorySalienceQuerySchema,
  MemorySalienceReportSchema,
  EvidenceGraphQuerySchema,
  EvidenceGraphSchema,
  GraphChannelQuerySchema,
  GraphChannelResponseSchema,
  StrategyOperationsQuerySchema,
  StrategyOperationsReportSchema,
  DrillManifestSchema,
  KnowledgeAlertSubscriptionSchema,
  KnowledgeAlertSubscriptionCreateSchema,
  KnowledgeAlertSubscriptionUpdateSchema,
  KnowledgeAlertSubscriptionListResponseSchema,
  KnowledgeAlertWebhookConfigSchema,
  KnowledgeAlertWebhookConfigUpsertSchema,
  KnowledgeObservabilityQuerySchema,
  KnowledgeObservabilityReportSchema,
  KnowledgeReleaseTagSchema,
  KnowledgeReleaseTagCreateSchema,
  KnowledgeReleaseTagUpdateSchema,
  KnowledgeReleaseGateHealthSchema,
  CreateCapabilityDefinitionSchema,
  PublishCapabilityVersionSchema,
  RecordCapabilityGapSchema,
  CapabilityDefinitionSchema,
  CapabilityCatalogEntrySchema,
  CapabilityVersionSchema,
  CapabilityGapSchema,
  CapabilityCatalogListQuerySchema,
  CapabilityGapListQuerySchema,
  SubmitCapabilityProposalSchema,
  CapabilityProposalSchema,
  CapabilityProposalDetailSchema,
  CapabilityApprovalSchema,
  CapabilityProposalListQuerySchema,
  RequestProposalInformationSchema,
  ApproveProposalSchema,
  RejectProposalSchema,
  RevokeProposalSchema,
  ReportRuntimeBindingSchema,
  RuntimeBindingHeartbeatSchema,
  ReportTrialOutcomeSchema,
  CapabilityRuntimeBindingSchema,
  CapabilityRuntimeBindingDetailSchema,
  CapabilityRuntimeBindingListQuerySchema,
  CapabilityTrialOutcomeSchema,
  RevokeRuntimeBindingSchema,
  CreateUsageRuleSchema,
  ReportUsageRuleEvaluationSchema,
  UsageRuleGuardSimulationSchema,
  UsageRuleSchema,
  UsageRuleDetailSchema,
  UsageRuleListQuerySchema,
  UsageRuleEvaluationSchema,
  UsageRuleGuardDecisionSchema,
  ActivateUsageRuleSchema,
  RetireUsageRuleSchema,
  RevokeUsageRuleSchema,
  CreateEnvironmentFactSchema,
  RevokeEnvironmentFactSchema,
  EnvironmentFactSchema,
  EnvironmentFactListQuerySchema,
  PromoteSkillSchema,
  ReportSkillTrialSchema,
  MemorySkillSchema,
  MemorySkillListQuerySchema,
  SkillActivateSchema,
  SkillRetireSchema,
  SkillRevokeSchema,
  type KnowledgeCapabilityManifest,
} from '../schemas/knowledge.schema';
import { KnowledgeSourceTypeSchema } from '../schemas/prisma-enums.generated';

const c = initContract();

export const knowledgeContract = c.router(
  {
    listConnectorCredentials: {
      method: 'GET',
      path: '/connector-credentials',
      query: z.object({ type: KnowledgeSourceTypeSchema.optional() }),
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(KnowledgeConnectorCredentialSchema)),
      },
      summary: 'List tenant-managed connector credentials',
    },
    dashboard: {
      method: 'GET',
      path: '/dashboard',
      responses: { 200: ApiResponseSchema(DashboardOverviewSchema) },
      summary: 'Knowledge operations overview',
    },
    listAccessibleTenants: {
      method: 'GET',
      path: '/tenants',
      query: KnowledgeTenantListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(KnowledgeTenantSummarySchema)),
      },
      summary: 'List knowledge tenants the caller can operate in',
    },
    listSpaces: {
      method: 'GET',
      path: '/spaces',
      query: KnowledgeListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(KnowledgeSpaceSchema)) },
      summary: 'List visible knowledge spaces',
    },
    createSpace: {
      method: 'POST',
      path: '/spaces',
      body: CreateSpaceSchema,
      responses: { 200: ApiResponseSchema(KnowledgeSpaceSchema) },
      summary: 'Create a knowledge space',
    },
    listSources: {
      method: 'GET',
      path: '/sources',
      query: KnowledgeSourceListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(KnowledgeSourceSchema)) },
      summary: 'List configured content sources',
    },
    createSource: {
      method: 'POST',
      path: '/sources',
      body: CreateSourceSchema,
      responses: { 200: ApiResponseSchema(KnowledgeSourceSchema) },
      summary: 'Configure a content source',
    },
    syncSource: {
      method: 'POST',
      path: '/sources/:sourceId/sync',
      pathParams: z.object({ sourceId: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: ApiResponseSchema(KnowledgeSourceSchema) },
      summary: 'Queue an authorized content source synchronization',
    },
    checkSource: {
      method: 'POST',
      path: '/sources/:sourceId/check',
      pathParams: z.object({ sourceId: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: ApiResponseSchema(CheckKnowledgeSourceResultSchema) },
      summary: 'Check source configuration without starting synchronization',
    },
    listDocuments: {
      method: 'GET',
      path: '/documents',
      query: KnowledgeDocumentListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(KnowledgeDocumentSchema)) },
      summary: 'List authorized documents',
    },
    createDocument: {
      method: 'POST',
      path: '/documents',
      body: CreateDocumentSchema,
      responses: { 200: ApiResponseSchema(KnowledgeDocumentSchema) },
      summary: 'Publish editor or uploaded text content',
    },
    uploadDocument: {
      method: 'POST',
      path: '/documents/upload',
      body: UploadKnowledgeDocumentSchema,
      responses: { 200: ApiResponseSchema(KnowledgeDocumentSchema) },
      summary: 'Store an original file and queue its knowledge extraction',
    },
    ingestFile: {
      method: 'POST',
      path: '/files/ingest',
      body: IngestExternalFileSchema,
      responses: { 200: ApiResponseSchema(ExternalFileIngestResultSchema) },
      summary: 'Ingest an authorized file link with parsed content into a knowledge space',
    },
    listDocumentPrincipals: {
      method: 'GET',
      path: '/documents/:documentId/principals',
      pathParams: z.object({ documentId: z.string().uuid() }),
      query: DocumentPrincipalListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(DocumentPrincipalSchema)),
      },
      summary: 'List document-level ACL principals for an authorized document',
    },
    grantDocumentPrincipal: {
      method: 'POST',
      path: '/documents/:documentId/principals',
      pathParams: z.object({ documentId: z.string().uuid() }),
      body: GrantDocumentPrincipalSchema,
      responses: { 200: ApiResponseSchema(DocumentPrincipalSchema) },
      summary: 'Grant a user, group or tenant principal access to an authorized document',
    },
    revokeDocumentPrincipal: {
      method: 'POST',
      path: '/documents/:documentId/principals/:principalId/revoke',
      pathParams: z.object({
        documentId: z.string().uuid(),
        principalId: z.string().uuid(),
      }),
      body: RevokeDocumentPrincipalSchema,
      responses: { 200: ApiResponseSchema(DocumentPrincipalSchema) },
      summary: 'Revoke a document principal; blocks access on the next PostgreSQL check',
    },
    listAclGrants: {
      method: 'GET',
      path: '/acl-grants',
      query: KnowledgeAclListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(KnowledgeAclGrantSchema)),
      },
      summary:
        'List resource-level ACL grants for the caller-manageable scope (includeRevoked/recover history)',
    },
    grantAcl: {
      method: 'POST',
      path: '/acl-grants',
      body: GrantKnowledgeAclSchema,
      responses: { 200: ApiResponseSchema(KnowledgeAclGrantSchema) },
      summary: 'Grant a principal an ACL permission on a resource (idempotent upsert)',
    },
    revokeAcl: {
      method: 'POST',
      path: '/acl-grants/:grantId/revoke',
      pathParams: z.object({ grantId: z.string().uuid() }),
      body: RevokeKnowledgeAclSchema,
      responses: { 200: ApiResponseSchema(KnowledgeAclGrantSchema) },
      summary: 'Revoke an ACL grant; blocks access on the next PostgreSQL check',
    },
    listPrincipals: {
      method: 'GET',
      path: '/principals',
      query: KnowledgePrincipalListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(KnowledgePrincipalSchema)),
      },
      summary: 'List tenant principals (users, groups, teams, services, agent runtimes)',
    },
    updatePrincipalStatus: {
      method: 'POST',
      path: '/principals/:principalId/status',
      pathParams: z.object({ principalId: z.string().uuid() }),
      body: UpdateKnowledgePrincipalStatusSchema,
      responses: { 200: ApiResponseSchema(KnowledgePrincipalSchema) },
      summary:
        'Suspend, re-activate or revoke a principal; revocation blocks on the next PostgreSQL check',
    },
    listApiKeyBindings: {
      method: 'GET',
      path: '/api-key-bindings',
      query: KnowledgeApiKeyListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(KnowledgeApiKeyBindingSchema)),
      },
      summary: 'List Model API key credential bindings for the tenant',
    },
    grantApiKeyBinding: {
      method: 'POST',
      path: '/api-key-bindings',
      body: GrantApiKeyBindingSchema,
      responses: { 200: ApiResponseSchema(KnowledgeApiKeyBindingSchema) },
      summary: 'Grant or refresh a Model API key binding (idempotent by keyId; scopes only narrow)',
    },
    revokeApiKeyBinding: {
      method: 'POST',
      path: '/api-key-bindings/:bindingId/revoke',
      pathParams: z.object({ bindingId: z.string().uuid() }),
      body: RevokeApiKeyBindingSchema,
      responses: { 200: ApiResponseSchema(KnowledgeApiKeyBindingSchema) },
      summary: 'Revoke an API key binding; blocks on the next PostgreSQL check',
    },
    getTenantPolicy: {
      method: 'GET',
      path: '/tenant-policy',
      responses: { 200: ApiResponseSchema(KnowledgePolicySchema) },
      summary: 'Read the tenant-level knowledge policy (defaults created lazily)',
    },
    updateTenantPolicy: {
      method: 'PUT',
      path: '/tenant-policy',
      body: UpdateKnowledgePolicySchema,
      responses: { 200: ApiResponseSchema(KnowledgePolicySchema) },
      summary:
        'Update the tenant policy (adminUserIds controls who may manage registries and grants)',
    },
    listPolicyApprovals: {
      method: 'GET',
      path: '/tenant-policy/approvals',
      query: KnowledgePolicyApprovalListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(KnowledgePolicyApprovalSchema)),
      },
      summary: 'List pending / decided approvals for actions gated by requireApprovalFor',
    },
    approvePolicyApproval: {
      method: 'POST',
      path: '/tenant-policy/approvals/:approvalId/approve',
      pathParams: z.object({ approvalId: z.string().uuid() }),
      body: DecideKnowledgePolicyApprovalSchema,
      responses: { 200: ApiResponseSchema(KnowledgePolicyApprovalSchema) },
      summary: 'Approve a pending approval (tenant admin only); triggers the original gated action',
    },
    rejectPolicyApproval: {
      method: 'POST',
      path: '/tenant-policy/approvals/:approvalId/reject',
      pathParams: z.object({ approvalId: z.string().uuid() }),
      body: DecideKnowledgePolicyApprovalSchema,
      responses: { 200: ApiResponseSchema(KnowledgePolicyApprovalSchema) },
      summary: 'Reject a pending approval (tenant admin only); no action is performed',
    },
    exportMemories: {
      method: 'POST',
      path: '/memories/export',
      body: MemoryExportQuerySchema,
      responses: { 200: ApiResponseSchema(MemoryExportResultSchema) },
      summary:
        'Export a structured result set of memories (high-risk read; gated by requireApprovalFor)',
    },
    listRecallTraces: {
      method: 'GET',
      path: '/recall-traces',
      query: RecallTraceListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(RecallTraceSchema)) },
      summary: 'List caller-owned recall traces (counts and hashes only; no query text or content)',
    },
    getRecallTrace: {
      method: 'GET',
      path: '/recall-traces/:traceId',
      pathParams: z.object({ traceId: z.string().uuid() }),
      responses: { 200: ApiResponseSchema(RecallTraceDetailSchema) },
      summary: 'Read one recall trace; results are re-filtered against the current ACL',
    },
    listSessionHandoffs: {
      method: 'GET',
      path: '/session-handoffs',
      query: SessionHandoffListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(SessionHandoffSchema)) },
      summary:
        'List caller-owned session handoffs (owner or shared); never returns foreign evidence',
    },
    getSessionHandoff: {
      method: 'GET',
      path: '/session-handoffs/:handoffId',
      pathParams: z.object({ handoffId: z.string().uuid() }),
      responses: { 200: ApiResponseSchema(SessionHandoffSchema) },
      summary: 'Read one handoff; revoked/forgotten evidence is dropped at read time',
    },
    listMemoryFeedbacks: {
      method: 'GET',
      path: '/memory-feedbacks',
      query: MemoryFeedbackListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(MemoryFeedbackSchema)) },
      summary: 'List caller-scoped feedback rows for memory or strategy (immutable audit trail)',
    },
    listEntityMerges: {
      method: 'GET',
      path: '/entity-merges',
      query: McpEntityMergeQuerySchema.optional(),
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(KnowledgeEntityMergeSchema)) },
      summary:
        'Caller-scoped entity-linking merge proposals (PROPOSED/ACCEPTED/REJECTED/REVERSED); visible only when caller can see at least one side; tenant admin only',
    },
    acceptEntityMerge: {
      method: 'POST',
      path: '/entity-merges/:mergeId/accept',
      pathParams: z.object({ mergeId: z.string().uuid() }),
      body: DecideEntityMergeSchema,
      responses: { 200: ApiResponseSchema(KnowledgeEntityMergeSchema) },
      summary:
        'Accept a PROPOSED merge; source assertion flips to MERGED and points at the canonical; ACL re-checked',
    },
    rejectEntityMerge: {
      method: 'POST',
      path: '/entity-merges/:mergeId/reject',
      pathParams: z.object({ mergeId: z.string().uuid() }),
      body: DecideEntityMergeSchema,
      responses: { 200: ApiResponseSchema(KnowledgeEntityMergeSchema) },
      summary:
        'Reject a PROPOSED merge (reviewNote required); merge row stays as REJECTED terminal, source assertion is not touched',
    },
    reverseEntityMerge: {
      method: 'POST',
      path: '/entity-merges/:mergeId/reverse',
      pathParams: z.object({ mergeId: z.string().uuid() }),
      body: DecideEntityMergeSchema,
      responses: { 200: ApiResponseSchema(KnowledgeEntityMergeSchema) },
      summary:
        'Reverse an ACCEPTED merge (reviewNote required); source assertion returns to CANDIDATE so graph projection can rebuild',
    },
    proposeEntityMerge: {
      method: 'POST',
      path: '/entity-merges/propose',
      body: ProposeEntityMergeContractSchema,
      responses: { 200: ApiResponseSchema(KnowledgeEntityMergeSchema) },
      summary:
        'Propose a new merge row (PROPOSED). Deterministic-key hits auto-ACCEPTED (closed set).',
    },
    listMemoryConflicts: {
      method: 'GET',
      path: '/memory-conflicts',
      query: MemoryConflictListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(MemoryConflictSchema)) },
      summary: 'List caller-scoped memory conflicts for triage and review',
    },
    getMemoryConflict: {
      method: 'GET',
      path: '/memory-conflicts/:conflictId',
      pathParams: z.object({ conflictId: z.string().uuid() }),
      responses: { 200: ApiResponseSchema(MemoryConflictSchema) },
      summary: 'Read one conflict; competing memory ids are re-filtered against the current ACL',
    },
    resolveMemoryConflict: {
      method: 'POST',
      path: '/memory-conflicts/:conflictId/resolve',
      pathParams: z.object({ conflictId: z.string().uuid() }),
      body: ResolveMemoryConflictSchema,
      responses: { 200: ApiResponseSchema(MemoryConflictSchema) },
      summary: 'Apply a resolution (SUPERSEDE/RETIRE/ADD_EVIDENCE/DISMISS) to an OPEN conflict',
    },
    memorySalience: {
      method: 'GET',
      path: '/memory/salience',
      query: MemorySalienceQuerySchema,
      responses: { 200: ApiResponseSchema(MemorySalienceReportSchema) },
      summary:
        'Recomputed salience read model per memory (feedback events + recall trace hits + confidence); never mutates Memory rows',
    },
    evidenceGraph: {
      method: 'GET',
      path: '/evidence/graph',
      query: EvidenceGraphQuerySchema,
      responses: { 200: ApiResponseSchema(EvidenceGraphSchema) },
      summary:
        'Read-only evidence graph for a root assertion/trace/memory; bodies are fetched per node via the current ACL',
    },
    boundedGraphChannel: {
      method: 'POST',
      path: '/memory/recall-graph',
      body: GraphChannelQuerySchema,
      responses: {
        200: ApiResponseSchema(GraphChannelResponseSchema),
        400: ApiResponseSchema(z.object({})),
      },
      summary:
        'Bounded GraphRAG (§8.2): BFS expansion with caller-side budget and predicate allowlist, ACL re-checked inside PG',
    },
    listCapabilityCatalog: {
      method: 'GET',
      path: '/capability-catalog',
      query: CapabilityCatalogListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(CapabilityCatalogEntrySchema)),
      },
      summary:
        'Read-only capability catalog (CapabilityDefinition + latestVersion); research-preview, not auto-installable',
    },
    createCapabilityDefinition: {
      method: 'POST',
      path: '/capability-definitions',
      body: CreateCapabilityDefinitionSchema,
      responses: { 200: ApiResponseSchema(CapabilityDefinitionSchema) },
      summary: 'Register a CapabilityDefinition with a fresh identifier',
    },
    publishCapabilityVersion: {
      method: 'POST',
      path: '/capability-definitions/:definitionId/versions',
      pathParams: z.object({ definitionId: z.string().uuid() }),
      body: PublishCapabilityVersionSchema,
      responses: { 200: ApiResponseSchema(CapabilityVersionSchema) },
      summary:
        'Publish an immutable CapabilityVersion snapshot (digest + riskFacts + policy facts)',
    },
    recordCapabilityGap: {
      method: 'POST',
      path: '/capability-gaps',
      body: RecordCapabilityGapSchema,
      responses: { 200: ApiResponseSchema(CapabilityGapSchema) },
      summary: 'Record a Capability Gap (open-only in C1; proposal/trial/resolution arrive in C2)',
    },
    listCapabilityGaps: {
      method: 'GET',
      path: '/capability-gaps',
      query: CapabilityGapListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(CapabilityGapSchema)),
      },
      summary: 'List open gaps scoped to caller space and (optionally) sensitivity class',
    },
    submitCapabilityProposal: {
      method: 'POST',
      path: '/capability-proposals',
      body: SubmitCapabilityProposalSchema,
      responses: { 200: ApiResponseSchema(CapabilityProposalSchema) },
      summary: 'Submit a proposal; idempotent on (tenantId, requesterId, idempotencyKey)',
    },
    listCapabilityProposals: {
      method: 'GET',
      path: '/capability-proposals',
      query: CapabilityProposalListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(CapabilityProposalSchema)),
      },
      summary: 'Caller-scoped proposal list with availableActions per row',
    },
    getCapabilityProposal: {
      method: 'GET',
      path: '/capability-proposals/:proposalId',
      pathParams: z.object({ proposalId: z.string().uuid() }),
      responses: { 200: ApiResponseSchema(CapabilityProposalDetailSchema) },
      summary: 'Read one proposal + immutable approval timeline + availableActions',
    },
    requestProposalInformation: {
      method: 'POST',
      path: '/capability-proposals/:proposalId/request-information',
      pathParams: z.object({ proposalId: z.string().uuid() }),
      body: RequestProposalInformationSchema,
      responses: { 200: ApiResponseSchema(CapabilityProposalSchema) },
      summary: 'Mark SUBMITTED -> NEEDS_INFO without changing the requested scope',
    },
    approveCapabilityProposal: {
      method: 'POST',
      path: '/capability-proposals/:proposalId/approve-trial',
      pathParams: z.object({ proposalId: z.string().uuid() }),
      body: ApproveProposalSchema,
      responses: { 200: ApiResponseSchema(CapabilityProposalSchema) },
      summary:
        'Append an APPROVE_TRIAL row; CRITICAL/HIGH require requiredApprovers distinct reviewers',
    },
    rejectCapabilityProposal: {
      method: 'POST',
      path: '/capability-proposals/:proposalId/reject',
      pathParams: z.object({ proposalId: z.string().uuid() }),
      body: RejectProposalSchema,
      responses: { 200: ApiResponseSchema(CapabilityProposalSchema) },
      summary: 'Append a REJECT row and transition SUBMITTED/NEEDS_INFO -> REJECTED',
    },
    revokeCapabilityProposal: {
      method: 'POST',
      path: '/capability-proposals/:proposalId/revoke',
      pathParams: z.object({ proposalId: z.string().uuid() }),
      body: RevokeProposalSchema,
      responses: { 200: ApiResponseSchema(CapabilityProposalSchema) },
      summary: 'Append a REVOKE row and transition any non-terminal state -> REVOKED (fail-closed)',
    },
    listCapabilityRuntimeBindings: {
      method: 'GET',
      path: '/capability-runtime-bindings',
      query: CapabilityRuntimeBindingListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(CapabilityRuntimeBindingSchema)),
      },
      summary: 'Caller-scoped binding list; status never claims READY unless lease is live',
    },
    getCapabilityRuntimeBinding: {
      method: 'GET',
      path: '/capability-runtime-bindings/:bindingId',
      pathParams: z.object({ bindingId: z.string().uuid() }),
      responses: { 200: ApiResponseSchema(CapabilityRuntimeBindingDetailSchema) },
      summary: 'Read one binding + immutable trial outcome timeline',
    },
    revokeCapabilityRuntimeBinding: {
      method: 'POST',
      path: '/capability-runtime-bindings/:bindingId/revoke',
      pathParams: z.object({ bindingId: z.string().uuid() }),
      body: RevokeRuntimeBindingSchema,
      responses: { 200: ApiResponseSchema(CapabilityRuntimeBindingSchema) },
      summary:
        'Emergency revoke: PostgreSQL blocks immediately (REVOKING) and a high-priority Outbox event notifies Agents',
    },
    createUsageRule: {
      method: 'POST',
      path: '/usage-rules',
      body: CreateUsageRuleSchema,
      responses: { 200: ApiResponseSchema(UsageRuleSchema) },
      summary:
        'Promote a successful Trial evidence into a UsageRule Candidate; idempotent on (tenantId,triggerSignature,spaceId)',
    },
    listUsageRules: {
      method: 'GET',
      path: '/usage-rules',
      query: UsageRuleListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(UsageRuleSchema)),
      },
      summary: 'Caller-scoped usage rule list with closed-set status filter',
    },
    getUsageRule: {
      method: 'GET',
      path: '/usage-rules/:usageRuleId',
      pathParams: z.object({ usageRuleId: z.string().uuid() }),
      responses: { 200: ApiResponseSchema(UsageRuleDetailSchema) },
      summary: 'Read one rule + immutable version + evaluation timeline',
    },
    simulateUsageRuleGuard: {
      method: 'POST',
      path: '/usage-rules/:usageRuleId/simulate-guard',
      pathParams: z.object({ usageRuleId: z.string().uuid() }),
      body: UsageRuleGuardSimulationSchema,
      responses: { 200: ApiResponseSchema(UsageRuleGuardDecisionSchema) },
      summary: 'Dry-run guard: only simulates the decision, never executes tools',
    },
    activateUsageRule: {
      method: 'POST',
      path: '/usage-rules/:usageRuleId/activate',
      pathParams: z.object({ usageRuleId: z.string().uuid() }),
      body: ActivateUsageRuleSchema,
      responses: { 200: ApiResponseSchema(UsageRuleSchema) },
      summary: 'Force-promote a TRIAL/CANDIDATE rule to ACTIVE; reasonCode required for audit',
    },
    retireUsageRule: {
      method: 'POST',
      path: '/usage-rules/:usageRuleId/retire',
      pathParams: z.object({ usageRuleId: z.string().uuid() }),
      body: RetireUsageRuleSchema,
      responses: { 200: ApiResponseSchema(UsageRuleSchema) },
      summary: 'Retire an ACTIVE/TRIAL rule with a reasonCode; non-terminal transition',
    },
    revokeUsageRule: {
      method: 'POST',
      path: '/usage-rules/:usageRuleId/revoke',
      pathParams: z.object({ usageRuleId: z.string().uuid() }),
      body: RevokeUsageRuleSchema,
      responses: { 200: ApiResponseSchema(UsageRuleSchema) },
      summary: 'Fail-closed revoke any non-terminal rule to RETIRED; bound by tenant + space',
    },
    createEnvironmentFact: {
      method: 'POST',
      path: '/environment-facts',
      body: CreateEnvironmentFactSchema,
      responses: { 200: ApiResponseSchema(EnvironmentFactSchema) },
      summary: 'Record an L3 environment fact (subject/predicate/object) scoped to a space',
    },
    listEnvironmentFacts: {
      method: 'GET',
      path: '/environment-facts',
      query: EnvironmentFactListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(EnvironmentFactSchema)),
      },
      summary: 'List caller-space environment facts with optional status filter',
    },
    revokeEnvironmentFact: {
      method: 'POST',
      path: '/environment-facts/:factId/revoke',
      pathParams: z.object({ factId: z.string().uuid() }),
      body: RevokeEnvironmentFactSchema,
      responses: { 200: ApiResponseSchema(EnvironmentFactSchema) },
      summary: 'Revoke an environment fact; blocks recall on the next PostgreSQL check',
    },
    promoteSkill: {
      method: 'POST',
      path: '/skills',
      body: PromoteSkillSchema,
      responses: { 200: ApiResponseSchema(MemorySkillSchema) },
      summary: 'Promote an ACTIVE strategy into a Skill candidate; idempotent on idempotencyKey',
    },
    listSkills: {
      method: 'GET',
      path: '/skills',
      query: MemorySkillListQuerySchema,
      responses: {
        200: ApiResponseSchema(PaginatedResponseSchema(MemorySkillSchema)),
      },
      summary: 'List caller-space skills with closed-set status filter',
    },
    activateSkill: {
      method: 'POST',
      path: '/skills/:skillId/activate',
      pathParams: z.object({ skillId: z.string().uuid() }),
      body: SkillActivateSchema,
      responses: { 200: ApiResponseSchema(MemorySkillSchema) },
      summary: 'Activate a TRIAL/CANDIDATE skill; reasonCode required for audit',
    },
    retireSkill: {
      method: 'POST',
      path: '/skills/:skillId/retire',
      pathParams: z.object({ skillId: z.string().uuid() }),
      body: SkillRetireSchema,
      responses: { 200: ApiResponseSchema(MemorySkillSchema) },
      summary: 'Retire a non-terminal skill with a reasonCode',
    },
    revokeSkill: {
      method: 'POST',
      path: '/skills/:skillId/revoke',
      pathParams: z.object({ skillId: z.string().uuid() }),
      body: SkillRevokeSchema,
      responses: { 200: ApiResponseSchema(MemorySkillSchema) },
      summary: 'Fail-closed revoke a skill to RETIRED; bound by tenant + space',
    },
    listMemories: {
      method: 'GET',
      path: '/memories',
      query: MemoryListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(MemorySchema)) },
      summary: 'List authorized memories',
    },
    createMemory: {
      method: 'POST',
      path: '/memories',
      body: CreateMemorySchema,
      responses: { 200: ApiResponseSchema(MemorySchema) },
      summary: 'Create a memory candidate or confirmed memory',
    },
    updateMemoryStatus: {
      method: 'PATCH',
      path: '/memories/:memoryId/status',
      pathParams: z.object({ memoryId: z.string().uuid() }),
      body: UpdateMemoryStatusSchema,
      responses: { 200: ApiResponseSchema(MemorySchema) },
      summary: 'Confirm or forget a memory',
    },
    listStrategies: {
      method: 'GET',
      path: '/strategies',
      query: MemoryStrategyListQuerySchema,
      responses: { 200: ApiResponseSchema(PaginatedResponseSchema(MemoryStrategySchema)) },
      summary: 'List ACL-scoped memory strategy candidates',
    },
    strategyOperations: {
      method: 'GET',
      path: '/strategies/operations',
      query: StrategyOperationsQuerySchema,
      responses: { 200: ApiResponseSchema(StrategyOperationsReportSchema) },
      summary:
        'Console operational metrics (§7.2): status mix, trial success, replay task queues, degraded watchlist, median candidate→trial wait; recomputed on read',
    },
    drillManifest: {
      method: 'GET',
      path: '/drills/manifest',
      responses: { 200: ApiResponseSchema(DrillManifestSchema) },
      summary:
        'Tenant drill evidence manifest (§9): authority counts, outbox watermark, projection READY counts, retention checks, SHA-256 fingerprint; tenant admins only',
    },
    observabilityReport: {
      method: 'GET',
      path: '/observability/report',
      query: KnowledgeObservabilityQuerySchema,
      responses: { 200: ApiResponseSchema(KnowledgeObservabilityReportSchema) },
      summary:
        'Production metrics read model (semantica §12): pipeline step status/lag/throughput, recall channel candidates and rejects, graph hop distribution, provenance chain failures, conflict backlog, decision outcomes, and an equally sized previous-window baseline; tenant admins only, recomputed on read',
    },
    listReleases: {
      method: 'GET',
      path: '/releases',
      responses: {
        200: ApiResponseSchema(
          z.object({
            list: z.array(KnowledgeReleaseTagSchema),
            total: z.number().int().nonnegative(),
          }),
        ),
      },
      summary:
        'List tenant release tags (semantica §12): admins only; tenantId+tag is unique; status drives CI gating (PROMOTED/HOLD/RETIRED)',
    },
    registerRelease: {
      method: 'POST',
      path: '/releases',
      body: KnowledgeReleaseTagCreateSchema,
      responses: { 201: ApiResponseSchema(KnowledgeReleaseTagSchema) },
      summary:
        'Register a new release tag (semantica §12): tenant admins only; duplicates are rejected; default status PROMOTED',
    },
    updateRelease: {
      method: 'PATCH',
      path: '/releases/:releaseId',
      body: KnowledgeReleaseTagUpdateSchema,
      responses: { 200: ApiResponseSchema(KnowledgeReleaseTagSchema) },
      summary:
        'Update release status/notes (semantica §12): admin only; stamps managedByUserId + changedAt; not allowed on missing releaseId',
    },
    releaseGateHealth: {
      method: 'GET',
      path: '/releases/:releaseId/gate-health',
      responses: { 200: ApiResponseSchema(KnowledgeReleaseGateHealthSchema) },
      summary:
        'Aggregated quality-gate health for one release (semantica §12): admin only; releaseBlocked unless status=PROMOTED and the latest quality report passed; historical pass/fail counts remain visible; blockedReasons is bounded 0..8',
    },
    listAlertSubscriptions: {
      method: 'GET',
      path: '/alert-subscriptions',
      responses: { 200: ApiResponseSchema(KnowledgeAlertSubscriptionListResponseSchema) },
      summary:
        'List my alert subscriptions (§12 console alerting): scoped to caller; section/severity/condition/channel all closed enums; condition=null denotes a coarse subscription under one section+severity',
    },
    createAlertSubscription: {
      method: 'POST',
      path: '/alert-subscriptions',
      body: KnowledgeAlertSubscriptionCreateSchema,
      responses: { 200: ApiResponseSchema(KnowledgeAlertSubscriptionSchema) },
      summary:
        'Subscribe to an alert channel (§12): caller-scoped; idempotent on (subscriberUserId, section, severity, condition, channel); condition=null denotes a coarse subscription',
    },
    updateAlertSubscription: {
      method: 'PATCH',
      path: '/alert-subscriptions/:subscriptionId',
      body: KnowledgeAlertSubscriptionUpdateSchema,
      responses: { 200: ApiResponseSchema(KnowledgeAlertSubscriptionSchema) },
      summary:
        'Toggle a subscription enabled flag (§12): caller-scoped (subscriberUserId must match); body is strict {enabled:boolean}',
    },
    deleteAlertSubscription: {
      method: 'DELETE',
      path: '/alert-subscriptions/:subscriptionId',
      body: z.object({}).optional(),
      responses: { 200: ApiResponseSchema(KnowledgeAlertSubscriptionSchema) },
      summary: 'Delete a subscription (§12): caller-scoped; returns the deleted record on success',
    },
    getAlertWebhookConfig: {
      method: 'GET',
      path: '/alert-channel-config/webhook',
      responses: { 200: ApiResponseSchema(KnowledgeAlertWebhookConfigSchema.nullable()) },
      summary:
        'Read the tenant-level webhook channel config (§12 alert push): admin only; null when not configured; never returns the secret plaintext, hasSecret indicates whether one is set',
    },
    putAlertWebhookConfig: {
      method: 'PUT',
      path: '/alert-channel-config/webhook',
      body: KnowledgeAlertWebhookConfigUpsertSchema,
      responses: { 200: ApiResponseSchema(KnowledgeAlertWebhookConfigSchema) },
      summary:
        'Upsert the tenant-level webhook channel config (§12 alert push): admin only; webhookUrl must be https; secret omitted keeps the current value, null clears it',
    },
    createStrategy: {
      method: 'POST',
      path: '/strategies',
      body: CreateMemoryStrategySchema,
      responses: { 200: ApiResponseSchema(MemoryStrategySchema) },
      summary: 'Create a cross-episode memory strategy candidate',
    },
    reportStrategyTrial: {
      method: 'POST',
      path: '/strategies/:strategyId/outcomes',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: ReportMemoryStrategyTrialSchema,
      responses: { 200: ApiResponseSchema(MemoryStrategySchema) },
      summary: 'Record an idempotent strategy trial outcome and advance its lifecycle',
    },
    enqueueStrategyReplay: {
      method: 'POST',
      path: '/strategies/:strategyId/replays',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: EnqueueMemoryStrategyReplaySchema,
      responses: {
        200: ApiResponseSchema(z.object({ id: z.string().uuid(), status: z.string() })),
      },
      summary: 'Queue an authorized replay task for a memory strategy',
    },
    createReplayPlan: {
      method: 'POST',
      path: '/strategies/:strategyId/replay-plans',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: CreateMemoryReplayPlanSchema,
      responses: { 200: ApiResponseSchema(MemoryReplayPlanSchema) },
      summary: 'Create a canonical replay task set and baseline specification',
    },
    requestBaselineGeneration: {
      method: 'POST',
      path: '/strategies/:strategyId/replay-plans/baseline/request',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: RequestMemoryStrategyBaselineSchema,
      responses: { 200: ApiResponseSchema(MemoryReplayPlanSchema) },
      summary: 'Queue baseline generation for a published replay plan',
    },
    reportBaselineGeneration: {
      method: 'POST',
      path: '/strategies/:strategyId/replay-plans/baseline/report',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: ReportMemoryStrategyBaselineSchema,
      responses: { 200: ApiResponseSchema(MemoryReplayPlanSchema) },
      summary: 'Record an external baseline generation result',
    },
    guardStrategyExecution: {
      method: 'POST',
      path: '/strategies/:strategyId/guard',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: MemoryStrategyExecutionContextSchema,
      responses: { 200: ApiResponseSchema(MemoryStrategyGuardResultSchema) },
      summary: 'Check whether a strategy may execute with the current tool and citations',
    },
    graph: {
      method: 'GET',
      path: '/graph',
      query: KnowledgeGraphQuerySchema,
      responses: { 200: ApiResponseSchema(KnowledgeGraphSchema) },
      summary: 'Read an ACL-scoped graph derived from authoritative knowledge data',
    },
    rebuildGraph: {
      method: 'POST',
      path: '/graph/rebuild',
      body: RebuildKnowledgeGraphSchema,
      responses: { 200: ApiResponseSchema(RebuildKnowledgeGraphResultSchema) },
      summary: 'Rebuild the authorized Neo4j knowledge graph projection',
    },
    putIntegrationObject: {
      method: 'PUT',
      path: '/integrations/objects',
      body: PutIntegrationObjectSchema,
      responses: { 200: ApiResponseSchema(IntegrationObjectMetadataSchema) },
      summary: 'Store a tenant and space scoped integration object',
    },
    readIntegrationObject: {
      method: 'POST',
      path: '/integrations/objects/read',
      body: IntegrationObjectReferenceSchema,
      responses: { 200: ApiResponseSchema(IntegrationObjectSchema) },
      summary: 'Read an authorized integration object',
    },
    deleteIntegrationObject: {
      method: 'POST',
      path: '/integrations/objects/delete',
      body: IntegrationObjectReferenceSchema,
      responses: { 200: ApiResponseSchema(DeleteIntegrationObjectResultSchema) },
      summary: 'Delete an authorized integration object',
    },
    putExternalGraphSnapshot: {
      method: 'PUT',
      path: '/integrations/graph-snapshots',
      body: PutExternalGraphSnapshotSchema,
      responses: { 200: ApiResponseSchema(ExternalGraphSnapshotSchema) },
      summary: 'Replace a tenant and space scoped external graph snapshot',
    },
    readExternalGraphSnapshot: {
      method: 'POST',
      path: '/integrations/graph-snapshots/read',
      body: ExternalGraphSnapshotReferenceSchema,
      responses: { 200: ApiResponseSchema(ExternalGraphSnapshotSchema) },
      summary: 'Read an authorized external graph snapshot',
    },
  },
  { pathPrefix: '/api/knowledge' },
);

export const yootunAgentContract = c.router(
  {
    search: {
      method: 'POST',
      path: '/search',
      body: KnowledgeSearchSchema,
      responses: { 200: ApiResponseSchema(KnowledgeSearchResponseSchema) },
      summary: 'Authorized lexical search for the yootun-agent knowledge plugin',
    },
    ingestFile: {
      method: 'POST',
      path: '/files/ingest',
      body: IngestExternalFileSchema,
      responses: {
        200: ApiResponseSchema(ExternalFileIngestResultSchema),
        401: ApiResponseSchema(z.object({})),
        403: ApiResponseSchema(z.object({})),
      },
      summary: 'Ingest an already-parsed file transcript so it is immediately lexically searchable',
    },
    overview: {
      method: 'GET',
      path: '/knowledge/overview',
      responses: {
        200: ApiResponseSchema(DashboardOverviewSchema),
        403: ApiResponseSchema(z.object({})),
      },
      summary: 'Read the caller tenant and ACL-scoped Knowledge dashboard overview',
    },
    onboardingStatus: {
      method: 'GET',
      path: '/onboarding/status',
      responses: {
        200: ApiResponseSchema(AgentOnboardingStatusSchema),
        403: ApiResponseSchema(z.object({})),
      },
      summary:
        'Read the verified runtime binding and capture health for agent onboarding (docs/0906/ai-memory §3.1)',
    },
    checkpoint: {
      method: 'POST',
      path: '/sessions/checkpoint',
      body: SessionCheckpointSchema,
      responses: {
        200: ApiResponseSchema(z.object({ accepted: z.boolean(), lastSequence: z.number().int() })),
      },
      summary: 'Idempotently persist an allowed session checkpoint',
    },
    remember: {
      method: 'POST',
      path: '/memory/remember',
      body: CreateMemorySchema,
      responses: { 200: ApiResponseSchema(MemorySchema) },
      summary: 'Remember a user-confirmed fact or submit a memory candidate',
    },
    recall: {
      method: 'POST',
      path: '/memory/recall',
      body: KnowledgeSearchSchema,
      responses: { 200: ApiResponseSchema(KnowledgeSearchResponseSchema) },
      summary: 'Authorized lexical recall of memories with evidence',
    },
    forget: {
      method: 'POST',
      path: '/memory/:memoryId/forget',
      pathParams: z.object({ memoryId: z.string().uuid() }),
      body: z.object({ reason: z.string().max(1000).optional() }),
      responses: { 200: ApiResponseSchema(MemorySchema) },
      summary: 'Immediately make a memory unavailable and queue projection cleanup',
    },
    scoreMemory: {
      method: 'POST',
      path: '/memory/:memoryId/score',
      pathParams: z.object({ memoryId: z.string().uuid() }),
      body: ScoreMemorySchema,
      responses: { 200: ApiResponseSchema(MemorySchema) },
      summary: 'Attach terminal and step-level value to a memory evidence candidate',
    },
    proposeStrategy: {
      method: 'POST',
      path: '/memory/strategies',
      body: CreateMemoryStrategySchema,
      responses: { 200: ApiResponseSchema(MemoryStrategySchema) },
      summary: 'Propose an ACL-scoped strategy from independently scored episodes',
    },
    reportStrategyTrial: {
      method: 'POST',
      path: '/memory/strategies/:strategyId/outcomes',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: ReportMemoryStrategyTrialSchema,
      responses: { 200: ApiResponseSchema(MemoryStrategySchema) },
      summary: 'Report an idempotent strategy trial outcome with validation evidence',
    },
    enqueueStrategyReplay: {
      method: 'POST',
      path: '/memory/strategies/:strategyId/replays',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: EnqueueMemoryStrategyReplaySchema,
      responses: {
        200: ApiResponseSchema(z.object({ id: z.string().uuid(), status: z.string() })),
      },
      summary: 'Queue a replay task for an authorized strategy',
    },
    createReplayPlan: {
      method: 'POST',
      path: '/memory/strategies/:strategyId/replay-plans',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: CreateMemoryReplayPlanSchema,
      responses: { 200: ApiResponseSchema(MemoryReplayPlanSchema) },
      summary: 'Create a canonical replay task set for an authorized strategy',
    },
    requestBaselineGeneration: {
      method: 'POST',
      path: '/memory/strategies/:strategyId/replay-plans/baseline/request',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: RequestMemoryStrategyBaselineSchema,
      responses: { 200: ApiResponseSchema(MemoryReplayPlanSchema) },
      summary: 'Queue baseline generation for an authorized replay plan',
    },
    reportBaselineGeneration: {
      method: 'POST',
      path: '/memory/strategies/:strategyId/replay-plans/baseline/report',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: ReportMemoryStrategyBaselineSchema,
      responses: { 200: ApiResponseSchema(MemoryReplayPlanSchema) },
      summary: 'Record an external baseline generation result',
    },
    guardStrategyExecution: {
      method: 'POST',
      path: '/memory/strategies/:strategyId/guard',
      pathParams: z.object({ strategyId: z.string().uuid() }),
      body: MemoryStrategyExecutionContextSchema,
      responses: { 200: ApiResponseSchema(MemoryStrategyGuardResultSchema) },
      summary: 'Check strategy execution boundaries and required citations',
    },
    finalizeSession: {
      method: 'POST',
      path: '/sessions/finalize',
      body: SessionFinalizeSchema,
      responses: { 200: ApiResponseSchema(SessionHandoffSchema) },
      summary: 'Idempotently close the source session and create a new OPEN Handoff',
    },
    continuation: {
      method: 'POST',
      path: '/sessions/continuation',
      body: SessionContinuationSchema,
      responses: { 200: ApiResponseSchema(SessionContinuationResponseSchema) },
      summary: 'Read caller-owned OPEN Handoffs and recompose a Briefing from authorized sources',
    },
    acceptHandoff: {
      method: 'POST',
      path: '/handoffs/:handoffId/accept',
      pathParams: z.object({ handoffId: z.string().uuid() }),
      body: HandoffAcceptSchema,
      responses: { 200: ApiResponseSchema(SessionHandoffAcceptResultSchema) },
      summary: 'Atomically bind an OPEN Handoff to the receiving session',
    },
    cancelHandoff: {
      method: 'POST',
      path: '/handoffs/:handoffId/cancel',
      pathParams: z.object({ handoffId: z.string().uuid() }),
      body: HandoffCancelSchema,
      responses: { 200: ApiResponseSchema(SessionHandoffCancelResultSchema) },
      summary: 'Cancel a caller-owned OPEN Handoff (non-shared only)',
    },
    recordFeedback: {
      method: 'POST',
      path: '/memory/feedback',
      body: RecordMemoryFeedbackSchema,
      responses: { 200: ApiResponseSchema(MemoryFeedbackSchema) },
      summary: 'Append an immutable MemoryFeedback row; never mutates the target',
    },
    feedbackAggregate: {
      method: 'GET',
      path: '/memory/feedback/aggregate',
      query: z.object({
        memoryId: z.string().uuid().optional(),
        strategyId: z.string().uuid().optional(),
      }),
      responses: { 200: ApiResponseSchema(MemoryFeedbackAggregateSchema) },
      summary: 'Compute helpful/not-helpful/stale/wrong/correction counts from feedback events',
    },
    reportRuntimeBinding: {
      method: 'POST',
      path: '/capability-bindings/report',
      body: ReportRuntimeBindingSchema,
      responses: { 200: ApiResponseSchema(CapabilityRuntimeBindingSchema) },
      summary:
        'Agents reports BINDING/READY/FAILED for an approved proposal; digest mismatch or scope escalation is rejected',
    },
    heartbeatRuntimeBinding: {
      method: 'POST',
      path: '/capability-bindings/:bindingId/heartbeat',
      pathParams: z.object({ bindingId: z.string().uuid() }),
      body: RuntimeBindingHeartbeatSchema,
      responses: { 200: ApiResponseSchema(CapabilityRuntimeBindingSchema) },
      summary:
        'Extend the lease of a READY/BINDING binding; expired or revoked bindings fail closed',
    },
    reportTrialOutcome: {
      method: 'POST',
      path: '/capability-bindings/:bindingId/outcomes',
      pathParams: z.object({ bindingId: z.string().uuid() }),
      body: ReportTrialOutcomeSchema,
      responses: { 200: ApiResponseSchema(CapabilityTrialOutcomeSchema) },
      summary:
        'Append an immutable trial outcome; idempotent on (tenantId, proposalId, idempotencyKey); budget overrun marks the trial failed',
    },
    reportUsageRuleEvaluation: {
      method: 'POST',
      path: '/usage-rules/:usageRuleId/evaluations',
      pathParams: z.object({ usageRuleId: z.string().uuid() }),
      body: ReportUsageRuleEvaluationSchema,
      responses: { 200: ApiResponseSchema(UsageRuleEvaluationSchema) },
      summary:
        'Paired replay report; idempotent on (tenantId, usageRuleVersionId, replayPlanId); safety violations block ACTIVE promotion',
    },
    reportSkillTrial: {
      method: 'POST',
      path: '/skills/:skillId/trials',
      pathParams: z.object({ skillId: z.string().uuid() }),
      body: ReportSkillTrialSchema,
      responses: { 200: ApiResponseSchema(MemorySkillSchema) },
      summary:
        'Report a skill trial; reliability = (pass+1)/(trial+2); corrections and boundary violations tighten or retire',
    },
  },
  { pathPrefix: '/api/yootun/v1' },
);

/**
 * Derives the yootun plugin capability manifest from the live ts-rest contract
 * so the console can never drift from the real API surface (review P2-02).
 */
export function listYootunAgentCapabilities(): KnowledgeCapabilityManifest {
  return {
    pluginBasePath: '/api/yootun/v1',
    retrievalMode: 'lexical-v1',
    endpoints: Object.entries(yootunAgentContract).map(([key, route]) => ({
      key,
      path: route.path,
      method: route.method,
      summary: route.summary ?? key,
    })),
  };
}
