import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
const root = new URL('../', import.meta.url)
test('publishes a web plugin with a bundle patch', async () => { const manifest = JSON.parse(await readFile(new URL('package.json', root), 'utf8')); assert.equal(manifest.name, '@dofe/dsh-yootun-content-command'); assert.equal(manifest.dsh.client.platform, 'web'); assert.equal(manifest.dsh.bundle.patch, './cordis.patch.yml') })
test('keeps multi-channel publishing behind explicit review', async () => { const [source, host] = await Promise.all([readFile(new URL('src/client.js', root), 'utf8'), readFile(new URL('index.js', root), 'utf8')]); for (const token of ['/api/desktop/yootun/content-command', 'review_article', 'select_platforms', 'publish_selected', '审核通过', '同步发送', 'AgentRuntime']) assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'u')); for (const platform of ['今日头条', '百度百家号', '小红书', '搜狐号']) assert.match(host, new RegExp(platform, 'u')); assert.doesNotMatch(source + host, /password|cookie|银行卡/iu) })
test('labels task metrics by scope and preserves missing values', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); for (const token of ['任务运行状况', '当前状态', '近 7 天执行表现', 'formatOptionalNumber', 'formatOptionalPercent', 'formatOptionalDuration']) assert.match(source, new RegExp(token, 'u')); assert.match(source, /parsed === null \? '—'/u); assert.doesNotMatch(source, /number\(performance\.success_rate\)\.toFixed/u) })
test('localizes known article workflow states without hiding extensions', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /draft: 'workflowDraft', published: 'workflowPublished'/u); assert.match(source, /workflowLabel\(article\.status, t\)/u); assert.match(source, /return key \? t\(key\) : value \|\| '—'/u); assert.doesNotMatch(source, /h\('dd', null, article\.status\)/u) })
test('uses only DSH alpha3 exported icons', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); const imports = source.match(/const \{([^}]+)\} = require\('@deepseek-ai\/dsh-client-ui-primitives'\)/u)?.[1] || ''; const exported = await readFile(new URL('../../../deepseek-harness/packages/client/ui-primitives/src/icons/index.tsx', root), 'utf8'); for (const name of imports.split(',').map(token => token.trim()).filter(token => token.startsWith('Icon'))) assert.match(exported, new RegExp(`export const ${name}\\b`, 'u')) })
test('maps status colors through desktop theme aliases', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); for (const token of ['--ycc-state-success', '--ycc-state-warning', '--ycc-state-error', '--dsw-alias-brand-primary', '--dsw-alias-label-tertiary', 'border-color:var(--ycc-state-success)']) assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'u')); assert.doesNotMatch(source, /#(?:22c55e|ef4444|f59e0b)\b/iu) })
test('announces loading and empty review states', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /className: 'ycc-loading', role: 'status'/u); assert.match(source, /className: 'ycc-empty', role: 'status'/u); assert.match(source, /'aria-busy': interactionBusy/u) })
test('distinguishes root service failures from empty content', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /!\['ready', 'empty', 'partial', 'degraded', 'warning'\]\.includes\(current\.status\)/u); assert.match(source, /className: 'ycc-empty ycc-root-state'/u); assert.match(source, /rootState === 'error' \? 'alert' : 'status'/u) })
test('prevents duplicate mutations and refresh overlap', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /if \(loadingRef\.current \|\| busyRef\.current\) return null/u); assert.match(source, /const refresh = \(\) => \{ if \(loadingRef\.current \|\| busyRef\.current\) return/u); assert.match(source, /'aria-label': t\('refresh'\), disabled: interactionBusy/u); assert.match(source, /busy: interactionBusy/u); assert.match(source, /\.ycc-header-buttons button:disabled\{opacity:\.45;cursor:default\}/u) })
test('freezes review navigation while a request is active', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /function ArticleList\(\{ articles, selectedId, onSelect, t, busy \}\)/u); assert.match(source, /'data-active': item\.articleId === selectedId, disabled: busy/u); assert.match(source, /'aria-selected': filter === item\[0\], key: item\[0\], disabled: busy/u); assert.match(source, /value: query, disabled: busy/u); assert.match(source, /'data-active': tab === 'overview', disabled: interactionBusy/u); assert.match(source, /'data-active': tab === 'review', disabled: interactionBusy/u); assert.match(source, /\.ycc-tabs button:disabled,.ycc-filter-tabs button:disabled,.ycc-search input:disabled,.ycc-list-item:disabled\{opacity:\.45;cursor:default\}/u) })
test('announces the empty article detail state', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /className: 'ycc-empty ycc-empty-detail', role: 'status'/u) })
test('lets the mobile review toolbar define its grid row height', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /@media\(max-width:820px\)[^\n]+\.ycc-review-workspace\{grid-template-rows:auto minmax\(0,1fr\)\}/u) })
