import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
const root = new URL('../', import.meta.url)
test('publishes a web plugin with a bundle patch', async () => { const manifest = JSON.parse(await readFile(new URL('package.json', root), 'utf8')); assert.equal(manifest.name, '@dofe/dsh-yootun-content-command'); assert.equal(manifest.dsh.client.platform, 'web'); assert.equal(manifest.dsh.bundle.patch, './cordis.patch.yml') })
test('keeps multi-channel publishing behind explicit review', async () => { const [source, host] = await Promise.all([readFile(new URL('src/client.js', root), 'utf8'), readFile(new URL('index.js', root), 'utf8')]); for (const token of ['/api/desktop/yootun/content-command', 'review_article', 'select_platforms', 'publish_selected', '审核通过', '同步发送', 'AgentRuntime']) assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'u')); for (const platform of ['今日头条', '百度百家号', '小红书', '搜狐号']) assert.match(host, new RegExp(platform, 'u')); assert.doesNotMatch(source + host, /password|cookie|银行卡/iu) })
test('labels task metrics by scope and preserves missing values', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); for (const token of ['任务运行状况', '当前状态', '近 7 天执行表现', 'formatOptionalNumber', 'formatOptionalPercent', 'formatOptionalDuration']) assert.match(source, new RegExp(token, 'u')); assert.match(source, /parsed === null \? '—'/u); assert.doesNotMatch(source, /number\(performance\.success_rate\)\.toFixed/u) })
test('uses only DSH alpha3 exported icons', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); const imports = source.match(/const \{([^}]+)\} = require\('@deepseek-ai\/dsh-client-ui-primitives'\)/u)?.[1] || ''; const exported = await readFile(new URL('../../../deepseek-harness/packages/client/ui-primitives/src/icons/index.tsx', root), 'utf8'); for (const name of imports.split(',').map(token => token.trim()).filter(token => token.startsWith('Icon'))) assert.match(exported, new RegExp(`export const ${name}\\b`, 'u')) })
test('keeps loading and action failures accessible without exposing raw errors', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /className: 'ycc-loading', role: 'status'/u); assert.match(source, /setError\('loadError'\)/u); assert.match(source, /setError\('actionError'\)/u); assert.doesNotMatch(source, /setError\(cause\.message\)/u); assert.match(source, /t\(error\)/u) })
test('blocks duplicate content mutations and announces pending work', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); for (const token of ['useRef', 'if (actionBusyRef.current) return null', 'actionBusyRef.current = true', 'actionBusyRef.current = false', "'aria-busy': loading || busy", "role: 'status'", "t('processing')"]) assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'u')) })
test('blocks conflicting refreshes and announces background loading', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); for (const token of ["disabled: loading || busy", "'aria-busy': loading || busy", "loading && data", "t('refreshing')", "refreshing: '正在刷新数据…'", "refreshing: 'Refreshing data…'"]) assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'u')) })
test('does not let an aborted content request clear a newer loading state', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); assert.match(source, /\.finally\(\(\) => \{ if \(!controller\.signal\.aborted\) setLoading\(false\) \}\)/u) })
test('moves focus into content command and restores its opener', async () => { const source = await readFile(new URL('src/client.js', root), 'utf8'); for (const token of ['document.activeElement', 'shellRef.current?.focus()', 'target.focus()', 'ref: shellRef', 'tabIndex: -1', 'closeOverlay()']) assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'u')); assert.match(source, /event\.key === 'Escape'\) closeOverlay\(\)/u); assert.match(source, /onClick: closeOverlay/u) })
