/** Generated by scripts/generate-product-identity.mjs from brand/brand.config.json. Do not edit directly. */

/** Raw identity table for both release channels. */
export const BRAND_RELEASE_IDENTITIES = Object.freeze({
  stable: Object.freeze({
    releaseChannel: 'stable' as const,
    packageName: "dsh-plugin-desktop",
    productName: "Yootun-Agent",
    appId: "ai.yootun.agent",
  }),
  beta: Object.freeze({
    releaseChannel: 'beta' as const,
    packageName: "dsh-plugin-desktop",
    productName: "Yootun-Agent Beta",
    appId: "ai.yootun.agent.beta",
  }),
})

/** Identity selected by brand.config.json activeChannel. */
export const BRAND_ACTIVE_CHANNEL = "beta" as const

/** Artifact filename prefix for the active channel, e.g. "Yootun-Agent-Beta". */
export const BRAND_ARTIFACT_PREFIX = "Yootun-Agent-Beta"

/** Electron Builder shortcutName for the active channel. */
export const BRAND_SHORTCUT_NAME = "Yootun-Agent Beta"

/** Display names shown in chrome that is identical across release channels. */
export const BRAND_DISPLAY_NAME = Object.freeze({
  titlebar: "Yootun-Agent",
  locale: "Yootun-Agent",
})

/** Update service contract served by the release infrastructure. */
export const BRAND_UPDATE_SERVICE = Object.freeze({
  endpoint: "https://ixicai.cn/api/desktop/version",
  versionHeader: "X-Yootun-Agent-Version",
  channelHeader: "X-Yootun-Agent-Channel",
})

/** Sidebar lockup display box consumed by the client brand slots. */
export const BRAND_WORDMARK_DISPLAY = Object.freeze({
  width: 200,
  height: 36,
})
