/** Private, local-only supply and operating risk workspace for Yootun-Agent. */

import { randomUUID } from 'node:crypto'
import { chmod, lstat, mkdir, readFile } from 'node:fs/promises'
import type { IncomingMessage, ServerResponse } from 'node:http'
import { dirname } from 'node:path'
import { writeFileAtomic } from '@deepseek-ai/dsh-atomic-write'

export const YOOTUN_SUPPLY_WATCH_PATH = '/api/desktop/yootun/supply-watch'
const STATE_VERSION = 1
const MAX_BODY_BYTES = 64 * 1024
const MAX_STATE_BYTES = 1024 * 1024
const MAX_RISKS = 1000
const MAX_ACTIONS = 1000
const DIRECTORY_MODE = 0o700
const FILE_MODE = 0o600
const CHECK_POSIX_MODE = process.platform !== 'win32'
const SEVERITIES = ['low', 'medium', 'high', 'critical'] as const
const RISK_STATUSES = ['open', 'monitoring', 'resolved'] as const
const ACTION_STATUSES = ['awaiting_confirmation', 'confirmed_pending_adapter', 'dismissed'] as const
type Severity = typeof SEVERITIES[number]
type RiskStatus = typeof RISK_STATUSES[number]
type ActionStatus = typeof ACTION_STATUSES[number]
type JsonRecord = Record<string, unknown>

export interface SupplyRisk { id: string; title: string; supplierLabel: string; category: string; severity: Severity; status: RiskStatus; signal: string; recommendedAction: string; source: string; dueAt?: string; updatedAt: string }
export interface SupplyAction { id: string; riskId: string; type: 'review_risk'; targetLabel: string; summary: string; status: ActionStatus; idempotencyKey: string; createdAt: string; updatedAt: string }
export interface SupplyState { version: 1; risks: SupplyRisk[]; actions: SupplyAction[]; updatedAt: string }
export interface SupplySnapshot extends SupplyState { dashboard: { risks: number; critical: number; open: number; dueToday: number; pendingConfirmation: number } }

class InvalidSupplyRequest extends Error {}
class SupplyBodyTooLarge extends Error {}
function record(value: unknown): JsonRecord | undefined { return typeof value === 'object' && value !== null && !Array.isArray(value) ? value as JsonRecord : undefined }
function exactKeys(value: JsonRecord, required: readonly string[], optional: readonly string[] = []): boolean { const allowed = new Set([...required, ...optional]); return required.every(key => Object.prototype.hasOwnProperty.call(value, key)) && Object.keys(value).every(key => allowed.has(key)) }
function text(value: unknown, label: string, max = 180): string { if (typeof value !== 'string') throw new InvalidSupplyRequest(`${label}_invalid`); const result = value.trim(); if (!result || result.length > max || /[\0\r]/u.test(result)) throw new InvalidSupplyRequest(`${label}_invalid`); return result }
function enumValue<T extends string>(value: unknown, options: readonly T[], label: string): T { if (typeof value !== 'string' || !options.includes(value as T)) throw new InvalidSupplyRequest(`${label}_invalid`); return value as T }
function canonicalTime(value: unknown): string | undefined { if (typeof value !== 'string') return undefined; const parsed = Date.parse(value); return Number.isFinite(parsed) && new Date(parsed).toISOString() === value ? value : undefined }
function emptyState(now: string): SupplyState { return { version: STATE_VERSION, risks: [], actions: [], updatedAt: now } }
function parseRisk(value: unknown): SupplyRisk | undefined { const item = record(value); if (!item || !exactKeys(item, ['id', 'title', 'supplierLabel', 'category', 'severity', 'status', 'signal', 'recommendedAction', 'source', 'updatedAt'], ['dueAt'])) return undefined; const updatedAt = canonicalTime(item.updatedAt); const dueAt = item.dueAt === undefined ? undefined : canonicalTime(item.dueAt); if (!updatedAt || (item.dueAt !== undefined && !dueAt)) return undefined; try { return { id: text(item.id, 'id', 80), title: text(item.title, 'title'), supplierLabel: text(item.supplierLabel, 'supplier_label', 80), category: text(item.category, 'category', 80), severity: enumValue(item.severity, SEVERITIES, 'severity'), status: enumValue(item.status, RISK_STATUSES, 'status'), signal: text(item.signal, 'signal', 500), recommendedAction: text(item.recommendedAction, 'recommended_action', 500), source: text(item.source, 'source', 80), ...(dueAt === undefined ? {} : { dueAt }), updatedAt } } catch { return undefined } }
function parseAction(value: unknown): SupplyAction | undefined { const item = record(value); if (!item || !exactKeys(item, ['id', 'riskId', 'type', 'targetLabel', 'summary', 'status', 'idempotencyKey', 'createdAt', 'updatedAt'])) return undefined; const createdAt = canonicalTime(item.createdAt); const updatedAt = canonicalTime(item.updatedAt); if (!createdAt || !updatedAt || item.type !== 'review_risk') return undefined; try { return { id: text(item.id, 'id', 80), riskId: text(item.riskId, 'risk_id', 80), type: 'review_risk', targetLabel: text(item.targetLabel, 'target_label'), summary: text(item.summary, 'summary', 500), status: enumValue(item.status, ACTION_STATUSES, 'status'), idempotencyKey: text(item.idempotencyKey, 'idempotency_key', 80), createdAt, updatedAt } } catch { return undefined } }
function parseState(value: unknown): SupplyState | undefined { const root = record(value); if (!root || !exactKeys(root, ['version', 'risks', 'actions', 'updatedAt']) || root.version !== STATE_VERSION || !Array.isArray(root.risks) || !Array.isArray(root.actions) || root.risks.length > MAX_RISKS || root.actions.length > MAX_ACTIONS) return undefined; const updatedAt = canonicalTime(root.updatedAt); const risks = root.risks.map(parseRisk); const actions = root.actions.map(parseAction); if (!updatedAt || risks.some(item => !item) || actions.some(item => !item)) return undefined; return { version: 1, risks: risks as SupplyRisk[], actions: actions as SupplyAction[], updatedAt } }
export async function readSupplyState(path: string, now = new Date().toISOString()): Promise<SupplyState> { try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink() || info.size > MAX_STATE_BYTES) return emptyState(now); return parseState(JSON.parse(await readFile(path, 'utf8'))) ?? emptyState(now) } catch { return emptyState(now) } }
async function writeState(path: string, state: SupplyState): Promise<void> { const directory = dirname(path); await mkdir(directory, { recursive: true, mode: DIRECTORY_MODE }); const info = await lstat(directory); if (!info.isDirectory() || info.isSymbolicLink()) throw new Error('supply_state_directory_invalid'); if (CHECK_POSIX_MODE) await chmod(directory, DIRECTORY_MODE); const json = `${JSON.stringify(state, undefined, 2)}\n`; if (Buffer.byteLength(json) > MAX_STATE_BYTES) throw new InvalidSupplyRequest('state_too_large'); await writeFileAtomic(path, json, { mode: FILE_MODE, dirMode: DIRECTORY_MODE }); if (CHECK_POSIX_MODE) await chmod(path, FILE_MODE) }
export function supplySnapshot(state: SupplyState, now = new Date()): SupplySnapshot { const today = now.toISOString().slice(0, 10); return { ...state, dashboard: { risks: state.risks.length, critical: state.risks.filter(item => item.severity === 'critical').length, open: state.risks.filter(item => item.status !== 'resolved').length, dueToday: state.risks.filter(item => item.dueAt?.slice(0, 10) === today && item.status !== 'resolved').length, pendingConfirmation: state.actions.filter(item => item.status === 'awaiting_confirmation').length } } }
function mutate(state: SupplyState, value: unknown, now: string): SupplyState { const body = record(value); if (!body || typeof body.action !== 'string') throw new InvalidSupplyRequest('request_invalid'); if (body.action === 'save_risk') { if (!exactKeys(body, ['action', 'title', 'supplierLabel', 'category', 'severity', 'status', 'signal', 'recommendedAction', 'source'], ['id', 'dueAt'])) throw new InvalidSupplyRequest('request_fields_invalid'); const id = body.id === undefined ? randomUUID() : text(body.id, 'id', 80); const dueAt = body.dueAt === undefined ? undefined : canonicalTime(body.dueAt); if (body.dueAt !== undefined && !dueAt) throw new InvalidSupplyRequest('due_at_invalid'); const risk: SupplyRisk = { id, title: text(body.title, 'title'), supplierLabel: text(body.supplierLabel, 'supplier_label', 80), category: text(body.category, 'category', 80), severity: enumValue(body.severity, SEVERITIES, 'severity'), status: enumValue(body.status, RISK_STATUSES, 'status'), signal: text(body.signal, 'signal', 500), recommendedAction: text(body.recommendedAction, 'recommended_action', 500), source: text(body.source, 'source', 80), ...(dueAt === undefined ? {} : { dueAt }), updatedAt: now }; if (!state.risks.some(item => item.id === id) && state.risks.length >= MAX_RISKS) throw new InvalidSupplyRequest('risk_limit_reached'); return { ...state, risks: [risk, ...state.risks.filter(item => item.id !== id)], updatedAt: now } }
  if (body.action === 'queue_review') { if (!exactKeys(body, ['action', 'riskId', 'summary'])) throw new InvalidSupplyRequest('request_fields_invalid'); const riskId = text(body.riskId, 'risk_id', 80); const risk = state.risks.find(item => item.id === riskId); if (!risk) throw new InvalidSupplyRequest('risk_not_found'); if (state.actions.length >= MAX_ACTIONS) throw new InvalidSupplyRequest('action_limit_reached'); const action: SupplyAction = { id: randomUUID(), riskId, type: 'review_risk', targetLabel: risk.supplierLabel, summary: text(body.summary, 'summary', 500), status: 'awaiting_confirmation', idempotencyKey: randomUUID(), createdAt: now, updatedAt: now }; return { ...state, actions: [action, ...state.actions], updatedAt: now } }
  if (body.action === 'confirm_action' || body.action === 'dismiss_action') { if (!exactKeys(body, ['action', 'id'])) throw new InvalidSupplyRequest('request_fields_invalid'); const id = text(body.id, 'id', 80); const action = state.actions.find(item => item.id === id); if (!action) throw new InvalidSupplyRequest('action_not_found'); if (action.status !== 'awaiting_confirmation') throw new InvalidSupplyRequest('action_not_pending'); const status: ActionStatus = body.action === 'confirm_action' ? 'confirmed_pending_adapter' : 'dismissed'; return { ...state, actions: state.actions.map(item => item.id === id ? { ...item, status, updatedAt: now } : item), updatedAt: now } }
  throw new InvalidSupplyRequest('action_invalid') }
const mutationQueues = new Map<string, Promise<void>>()
async function mutateSupplyState(path: string, value: unknown, now: string): Promise<SupplyState> { const previous = mutationQueues.get(path) ?? Promise.resolve(); let release: (() => void) | undefined; const current = new Promise<void>(resolve => { release = resolve }); const chain = previous.then(() => current); mutationQueues.set(path, chain); await previous; try { const next = mutate(await readSupplyState(path, now), value, now); await writeState(path, next); return next } finally { release?.(); if (mutationQueues.get(path) === chain) mutationQueues.delete(path) } }
function finish(res: ServerResponse, status: number, value: object, allow?: string): void { res.statusCode = status; res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.setHeader('Cache-Control', 'no-store'); if (allow) res.setHeader('Allow', allow); res.end(JSON.stringify(value)) }
async function body(req: IncomingMessage): Promise<unknown> { let size = 0; const chunks: Buffer[] = []; for await (const chunk of req) { const data = Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)); size += data.byteLength; if (size > MAX_BODY_BYTES) throw new SupplyBodyTooLarge(); chunks.push(data) } try { return JSON.parse(Buffer.concat(chunks).toString('utf8')) } catch { throw new InvalidSupplyRequest('json_invalid') } }
export async function handleYootunSupplyWatchRequest(req: IncomingMessage, res: ServerResponse, rendererOrigin: string, options: { statePath: string | undefined }): Promise<void> { if (req.headers.origin && req.headers.origin !== rendererOrigin) { finish(res, 403, { error: 'origin_forbidden' }); return } const path = options.statePath; if (!path) { finish(res, 503, { error: 'state_unavailable' }); return } const now = new Date().toISOString(); try { if (req.method === 'GET') { finish(res, 200, supplySnapshot(await readSupplyState(path, now))); return } if (req.method !== 'POST') { finish(res, 405, { error: 'method_not_allowed' }, 'GET, POST'); return } const next = await mutateSupplyState(path, await body(req), now); finish(res, 200, supplySnapshot(next)) } catch (cause) { if (cause instanceof SupplyBodyTooLarge) { finish(res, 413, { error: 'body_too_large' }); return } if (cause instanceof InvalidSupplyRequest) { finish(res, 400, { error: cause.message }); return } finish(res, 500, { error: 'state_write_failed' }) } }
