/** Private, local-only approval queue and audit record for Yootun-Agent. */
import { randomUUID } from 'node:crypto'
import { chmod, lstat, mkdir, readFile } from 'node:fs/promises'
import type { IncomingMessage, ServerResponse } from 'node:http'
import { dirname } from 'node:path'
import { writeFileAtomic } from '@deepseek-ai/dsh-atomic-write'
export const YOOTUN_APPROVALS_PATH = '/api/desktop/yootun/approvals'
const VERSION = 1; const MAX_BODY = 64 * 1024; const MAX_STATE = 1024 * 1024; const MAX_ACTIONS = 2000; const DIR_MODE = 0o700; const FILE_MODE = 0o600; const POSIX = process.platform !== 'win32'; const STATUSES = ['awaiting_confirmation', 'confirmed_pending_adapter', 'dismissed', 'succeeded', 'failed', 'requires_user_login'] as const
type Status = typeof STATUSES[number]; type RecordValue = Record<string, unknown>
export type ApprovalAdapterStatus = 'succeeded' | 'failed' | 'requires_user_login'
export interface ApprovalAdapterRequest { actionId: string; source: string; targetLabel: string; summary: string; risk: 'high' | 'critical'; idempotencyKey: string }
export interface ApprovalAdapterResult { status: ApprovalAdapterStatus; reasonCode: string; completedAt?: string; remoteRef?: string }
export interface ApprovalAdapter { execute: (request: ApprovalAdapterRequest) => Promise<ApprovalAdapterResult> }
export interface ApprovalAdapterReceipt { status: ApprovalAdapterStatus; reasonCode: string; completedAt: string; remoteRef?: string }
export interface ApprovalAction { id: string; source: string; targetLabel: string; summary: string; risk: 'high' | 'critical'; status: Status; idempotencyKey: string; createdAt: string; updatedAt: string; adapterReceipt?: ApprovalAdapterReceipt }
export interface ApprovalState { version: 1; actions: ApprovalAction[]; updatedAt: string }
export interface ApprovalSnapshot extends ApprovalState { dashboard: { pending: number; confirmed: number; dismissed: number } }
class InvalidApprovalRequest extends Error {}; class ApprovalBodyTooLarge extends Error {}
const record = (value: unknown): RecordValue | undefined => typeof value === 'object' && value !== null && !Array.isArray(value) ? value as RecordValue : undefined
const exactKeys = (value: RecordValue, required: readonly string[], optional: readonly string[] = []) => { const allowed = new Set([...required, ...optional]); return required.every(key => Object.prototype.hasOwnProperty.call(value, key)) && Object.keys(value).every(key => allowed.has(key)) }
const text = (value: unknown, label: string, max = 500) => { if (typeof value !== 'string') throw new InvalidApprovalRequest(`${label}_invalid`); const result = value.trim(); if (!result || result.length > max || /[\0\r]/u.test(result)) throw new InvalidApprovalRequest(`${label}_invalid`); return result }
const time = (value: unknown) => { if (typeof value !== 'string') return undefined; const parsed = Date.parse(value); return Number.isFinite(parsed) && new Date(parsed).toISOString() === value ? value : undefined }
const emptyState = (now: string): ApprovalState => ({ version: VERSION, actions: [], updatedAt: now })
function parseAction(value: unknown): ApprovalAction | undefined { const item = record(value); if (!item || !exactKeys(item, ['id', 'source', 'targetLabel', 'summary', 'risk', 'status', 'idempotencyKey', 'createdAt', 'updatedAt'], ['adapterReceipt'])) return undefined; const createdAt = time(item.createdAt); const updatedAt = time(item.updatedAt); if (!createdAt || !updatedAt) return undefined; try { const status = STATUSES.includes(item.status as Status) ? item.status as Status : (() => { throw new InvalidApprovalRequest('status_invalid') })(); const rawReceipt = item.adapterReceipt; let adapterReceipt: ApprovalAdapterReceipt | undefined; if (rawReceipt !== undefined) { const receipt = record(rawReceipt); if (!receipt) return undefined; const completedAt = time(receipt.completedAt); const receiptStatus = typeof receipt.status === 'string' && ['succeeded', 'failed', 'requires_user_login'].includes(receipt.status) ? receipt.status as ApprovalAdapterStatus : undefined; const reasonCode = typeof receipt.reasonCode === 'string' && /^[a-z0-9_:-]{1,80}$/u.test(receipt.reasonCode) ? receipt.reasonCode : undefined; const remoteRef = receipt.remoteRef === undefined ? undefined : typeof receipt.remoteRef === 'string' && receipt.remoteRef.length <= 160 && !/[\0\r\n]/u.test(receipt.remoteRef) ? receipt.remoteRef : undefined; if (!completedAt || !receiptStatus || !reasonCode || (receipt.remoteRef !== undefined && remoteRef === undefined)) return undefined; adapterReceipt = { status: receiptStatus, reasonCode, completedAt, ...(remoteRef === undefined ? {} : { remoteRef }) } } const terminal = status === 'succeeded' || status === 'failed' || status === 'requires_user_login'; if (terminal !== (adapterReceipt !== undefined) || (adapterReceipt !== undefined && adapterReceipt.status !== status)) return undefined; return { id: text(item.id, 'id', 80), source: text(item.source, 'source', 80), targetLabel: text(item.targetLabel, 'target_label', 160), summary: text(item.summary, 'summary'), risk: item.risk === 'critical' ? 'critical' : item.risk === 'high' ? 'high' : (() => { throw new InvalidApprovalRequest('risk_invalid') })(), status, idempotencyKey: text(item.idempotencyKey, 'idempotency_key', 80), createdAt, updatedAt, ...(adapterReceipt === undefined ? {} : { adapterReceipt }) } } catch { return undefined } }
function parseState(value: unknown): ApprovalState | undefined { const root = record(value); if (!root || !exactKeys(root, ['version', 'actions', 'updatedAt']) || root.version !== VERSION || !Array.isArray(root.actions) || root.actions.length > MAX_ACTIONS) return undefined; const updatedAt = time(root.updatedAt); const actions = root.actions.map(parseAction); if (!updatedAt || actions.some(item => !item)) return undefined; return { version: VERSION, actions: actions as ApprovalAction[], updatedAt } }
export async function readApprovalState(path: string, now = new Date().toISOString()): Promise<ApprovalState> { try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink() || info.size > MAX_STATE) return emptyState(now); return parseState(JSON.parse(await readFile(path, 'utf8'))) ?? emptyState(now) } catch { return emptyState(now) } }
async function writeState(path: string, state: ApprovalState) { const dir = dirname(path); await mkdir(dir, { recursive: true, mode: DIR_MODE }); const info = await lstat(dir); if (!info.isDirectory() || info.isSymbolicLink()) throw new Error('approval_state_directory_invalid'); if (POSIX) await chmod(dir, DIR_MODE); await writeFileAtomic(path, `${JSON.stringify(state, undefined, 2)}\n`, { mode: FILE_MODE, dirMode: DIR_MODE }); if (POSIX) await chmod(path, FILE_MODE) }
export function approvalSnapshot(state: ApprovalState): ApprovalSnapshot { return { ...state, dashboard: { pending: state.actions.filter(item => item.status === 'awaiting_confirmation').length, confirmed: state.actions.filter(item => item.status === 'confirmed_pending_adapter').length, dismissed: state.actions.filter(item => item.status === 'dismissed').length } } }
function mutate(state: ApprovalState, value: unknown, now: string): ApprovalState { const body = record(value); if (!body || typeof body.action !== 'string') throw new InvalidApprovalRequest('request_invalid'); if (body.action === 'enqueue') { if (!exactKeys(body, ['action', 'source', 'targetLabel', 'summary', 'risk'], ['idempotencyKey'])) throw new InvalidApprovalRequest('request_fields_invalid'); const source = text(body.source, 'source', 80); const targetLabel = text(body.targetLabel, 'target_label', 160); const summary = text(body.summary, 'summary'); const risk: ApprovalAction['risk'] = body.risk === 'critical' ? 'critical' : body.risk === 'high' ? 'high' : (() => { throw new InvalidApprovalRequest('risk_invalid') })(); const idempotencyKey = body.idempotencyKey === undefined ? randomUUID() : text(body.idempotencyKey, 'idempotency_key', 80); const existing = state.actions.find(action => action.idempotencyKey === idempotencyKey); if (existing) { if (existing.source !== source || existing.targetLabel !== targetLabel || existing.summary !== summary || existing.risk !== risk) throw new InvalidApprovalRequest('idempotency_key_conflict'); return state } if (state.actions.length >= MAX_ACTIONS) throw new InvalidApprovalRequest('action_limit_reached'); const action: ApprovalAction = { id: randomUUID(), source, targetLabel, summary, risk, status: 'awaiting_confirmation', idempotencyKey, createdAt: now, updatedAt: now }; return { ...state, actions: [action, ...state.actions], updatedAt: now } } if (body.action === 'confirm' || body.action === 'dismiss') { if (!exactKeys(body, ['action', 'id'])) throw new InvalidApprovalRequest('request_fields_invalid'); const id = text(body.id, 'id', 80); const item = state.actions.find(action => action.id === id); if (!item || item.status !== 'awaiting_confirmation') throw new InvalidApprovalRequest('action_not_pending'); const status: Status = body.action === 'confirm' ? 'confirmed_pending_adapter' : 'dismissed'; return { ...state, actions: state.actions.map(action => action.id === id ? { ...action, status, updatedAt: now } : action), updatedAt: now } } throw new InvalidApprovalRequest('action_invalid') }
const queues = new Map<string, Promise<void>>(); async function mutateState(path: string, value: unknown, now: string) { const previous = queues.get(path) ?? Promise.resolve(); let release: (() => void) | undefined; const current = new Promise<void>(resolve => { release = resolve }); const chain = previous.then(() => current); queues.set(path, chain); await previous; try { const next = mutate(await readApprovalState(path, now), value, now); await writeState(path, next); return next } finally { release?.(); if (queues.get(path) === chain) queues.delete(path) } }
function approvalAdapterReceipt(value: unknown, fallbackTime: string): ApprovalAdapterReceipt { const item = record(value); const status = item?.status; const reasonCode = item?.reasonCode; const completedAt = item?.completedAt; const remoteRef = item?.remoteRef; if ((status !== 'succeeded' && status !== 'failed' && status !== 'requires_user_login') || typeof reasonCode !== 'string' || !/^[a-z0-9_:-]{1,80}$/u.test(reasonCode) || (completedAt !== undefined && time(completedAt) === undefined) || (remoteRef !== undefined && (typeof remoteRef !== 'string' || remoteRef.length > 160 || /[\0\r\n]/u.test(remoteRef)))) return { status: 'failed', reasonCode: 'adapter_invalid_result', completedAt: fallbackTime }; return { status, reasonCode, completedAt: typeof completedAt === 'string' ? completedAt : fallbackTime, ...(typeof remoteRef === 'string' ? { remoteRef } : {}) } }
export async function executeApprovalAction(path: string, actionId: string, adapter: ApprovalAdapter | undefined, now = new Date().toISOString()): Promise<ApprovalSnapshot> { const previous = queues.get(path) ?? Promise.resolve(); let release: (() => void) | undefined; const current = new Promise<void>(resolve => { release = resolve }); const chain = previous.then(() => current); queues.set(path, chain); await previous; try { const state = await readApprovalState(path, now); const action = state.actions.find(item => item.id === actionId); if (!action) throw new InvalidApprovalRequest('action_not_found'); if (action.status === 'awaiting_confirmation') throw new InvalidApprovalRequest('action_not_confirmed'); if (action.status === 'dismissed' || action.status === 'succeeded') return approvalSnapshot(state); if (!adapter) throw new InvalidApprovalRequest('approval_adapter_unavailable'); let result: ApprovalAdapterResult; try { result = await adapter.execute({ actionId: action.id, source: action.source, targetLabel: action.targetLabel, summary: action.summary, risk: action.risk, idempotencyKey: action.idempotencyKey }) } catch { result = { status: 'failed', reasonCode: 'adapter_failed' } } const receipt = approvalAdapterReceipt(result, now); const next: ApprovalState = { ...state, actions: state.actions.map(item => item.id === action.id ? { ...item, status: receipt.status, adapterReceipt: receipt, updatedAt: receipt.completedAt } : item), updatedAt: receipt.completedAt }; await writeState(path, next); return approvalSnapshot(next) } finally { release?.(); if (queues.get(path) === chain) queues.delete(path) } }
const finish = (res: ServerResponse, status: number, value: object, allow?: string) => { res.statusCode = status; res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.setHeader('Cache-Control', 'no-store'); if (allow) res.setHeader('Allow', allow); res.end(JSON.stringify(value)) }
async function requestBody(req: IncomingMessage) { let size = 0; const chunks: Buffer[] = []; for await (const chunk of req) { const data = Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)); size += data.byteLength; if (size > MAX_BODY) throw new ApprovalBodyTooLarge(); chunks.push(data) } try { return JSON.parse(Buffer.concat(chunks).toString('utf8')) } catch { throw new InvalidApprovalRequest('json_invalid') } }
export async function handleYootunApprovalsRequest(req: IncomingMessage, res: ServerResponse, rendererOrigin: string, options: { statePath: string | undefined; adapter?: ApprovalAdapter | undefined }): Promise<void> { if (req.headers.origin && req.headers.origin !== rendererOrigin) { finish(res, 403, { error: 'origin_forbidden' }); return } const path = options.statePath; if (!path) { finish(res, 503, { error: 'state_unavailable' }); return } const now = new Date().toISOString(); try { if (req.method === 'GET') { finish(res, 200, approvalSnapshot(await readApprovalState(path, now))); return } if (req.method !== 'POST') { finish(res, 405, { error: 'method_not_allowed' }, 'GET, POST'); return } const payload = await requestBody(req); const request = record(payload); if (request?.action === 'execute_action') { if (!exactKeys(request, ['action', 'id'])) throw new InvalidApprovalRequest('request_fields_invalid'); finish(res, 200, await executeApprovalAction(path, text(request.id, 'id', 80), options.adapter, now)); return } finish(res, 200, approvalSnapshot(await mutateState(path, payload, now))) } catch (cause) { if (cause instanceof ApprovalBodyTooLarge) { finish(res, 413, { error: 'body_too_large' }); return } if (cause instanceof InvalidApprovalRequest) { finish(res, cause.message === 'approval_adapter_unavailable' ? 503 : 400, { error: cause.message }); return } finish(res, 500, { error: 'state_write_failed' }) } }
