window.__ModuleLoader__.load({
  id: "@dofe/dsh-yootun-daily-report",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    const React = require('react')
    const { createElement: h, useEffect, useState, useSyncExternalStore } = React
    const { IconCloseOutline16, IconRefreshOutline16, IconDataOutline16, Tooltip } = require('@deepseek-ai/dsh-client-ui-primitives')
    const NS = 'dofe.yootun-daily-report'; const PATH = '/api/desktop/yootun/daily-report'
    const copy = { zh: { open: '昨日工作', title: '昨日工作日报', subtitle: '汇总本机 Agent 会话与工具调用', close: '关闭昨日工作日报', refresh: '刷新', sessions: '会话', turns: '轮次', completed: '完成', failed: '异常', tools: '工具调用', empty: '昨日没有可汇总的工作记录', unavailable: '本机事件暂不可用', privacy: '仅展示标题、工作区与聚合计数，不展示会话正文。', sources: '数据源状态', local: '本机事件', toolsSource: '工具目录', salesIntent: '销售意向', retrofit: '改装检索', knowledge: '企业知识', sourceReady: '已就绪', sourceEmpty: '无数据', sourceUnavailable: '不可用', sourceError: '异常', reason: '原因' }, en: { open: 'Yesterday', title: 'Yesterday at a glance', subtitle: 'Local Agent sessions and tool calls', close: 'Close yesterday report', refresh: 'Refresh', sessions: 'Sessions', turns: 'Turns', completed: 'Completed', failed: 'Failed', tools: 'Tool calls', empty: 'No local work recorded yesterday', unavailable: 'Local events unavailable', privacy: 'Titles, workspaces, and aggregates only; conversation text is excluded.', sources: 'Source status', local: 'Local events', toolsSource: 'Tool catalog', salesIntent: 'Sales intent', retrofit: 'Retrofit', knowledge: 'Knowledge', sourceReady: 'Ready', sourceEmpty: 'No data', sourceUnavailable: 'Unavailable', sourceError: 'Error', reason: 'Reason' } }
    let opened = false; const listeners = new Set(); const emit = () => listeners.forEach(listener => listener()); const setOpened = value => { opened = value; emit() }; const subscribe = listener => { listeners.add(listener); return () => listeners.delete(listener) }; const snapshot = () => opened
    function statusLabel(status, t) { return status === 'ready' ? t('sourceReady') : status === 'empty' ? t('sourceEmpty') : status === 'error' ? t('sourceError') : t('sourceUnavailable') }
    function Overlay({ t }) { const visible = useSyncExternalStore(subscribe, snapshot, snapshot); const [data, setData] = useState(null); const [revision, setRevision] = useState(0); useEffect(() => { if (!visible) return undefined; const controller = new AbortController(); void fetch(PATH, { credentials: 'same-origin', signal: controller.signal, headers: { Accept: 'application/json' } }).then(response => response.json()).then(setData).catch(() => setData({ activity: { status: 'unavailable', reason: 'request_failed' } })); return () => controller.abort() }, [visible, revision]); if (!visible) return null; const activity = data?.activity; const totals = activity?.totals || {}; const metricValue = value => activity?.status === 'unavailable' || activity?.status === 'error' ? '不可用' : String(value ?? 0); const metrics = [['sessions', totals.sessions], ['turns', totals.turns], ['completed', totals.completed], ['failed', totals.failed], ['tools', totals.toolCalls]]; const sourceRows = [['local', data?.sources?.local || activity], ['toolsSource', data?.sources?.tools], ['salesIntent', data?.sources?.salesIntent], ['retrofit', data?.sources?.retrofit], ['knowledge', data?.sources?.knowledge]]; return h('div', { className: 'ydr-overlay' }, h('main', { className: 'ydr-shell' }, h('header', { className: 'ydr-header' }, h('div', null, h('h1', null, t('title')), h('p', null, t('subtitle'))), h('div', { className: 'ydr-actions' }, h(Tooltip, { label: t('refresh') }, h('button', { type: 'button', 'aria-label': t('refresh'), onClick: () => setRevision(value => value + 1) }, h(IconRefreshOutline16, { size: 16 }))), h(Tooltip, { label: t('close') }, h('button', { type: 'button', 'aria-label': t('close'), onClick: () => setOpened(false) }, h(IconCloseOutline16, { size: 16 }))))), h('div', { className: 'ydr-content' }, h('div', { className: 'ydr-metrics' }, ...metrics.map(([label, value]) => h('div', { className: 'ydr-metric', key: label }, h('span', null, t(label)), h('strong', null, metricValue(value)))), h('p', { className: 'ydr-privacy' }, t('privacy')), h('section', { className: 'ydr-sources' }, h('h2', null, t('sources')), ...sourceRows.map(([label, source]) => h('div', { className: 'ydr-source-row', key: label }, h('span', null, t(label)), h('b', { className: `ydr-source-${source?.status || 'unavailable'}` }, statusLabel(source?.status, t)), source?.reason ? h('code', null, `${t('reason')}: ${source.reason}`) : null))), activity?.status === 'unavailable' || activity?.status === 'error' ? h('div', { className: 'ydr-empty', role: 'alert' }, t('unavailable')) : activity?.status === 'empty' ? h('div', { className: 'ydr-empty' }, t('empty')) : h('section', { className: 'ydr-section' }, (activity?.sessions || []).map(item => h('article', { className: 'ydr-row', key: `${item.workspace}-${item.title}` }, h('strong', null, item.title), h('span', null, `${item.workspace} · ${item.turns} ${t('turns')}`)))))) ) }
    function Button({ t }) { return h(Tooltip, { label: t('open') }, h('button', { type: 'button', className: 'ydr-button', 'aria-label': t('open'), onClick: () => setOpened(true) }, h(IconDataOutline16, { size: 18 }))) }
    const sourceStateCss = '.ydr-source-row{align-items:center;gap:10px;flex-wrap:wrap}.ydr-source-row>span{min-width:0}.ydr-source-row code{max-width:100%;overflow-wrap:anywhere;color:var(--dsw-alias-label-secondary);font-size:11px}.ydr-source-ready{color:var(--dsw-alias-state-success-primary)}.ydr-source-error{color:var(--dsw-alias-state-error-primary)}'
    function apply(ctx) { ctx.effect(() => ctx.locale.register(NS, copy), 'dofe-yootun-daily-report: dictionaries'); ctx.effect(() => { const style = document.createElement('style'); style.dataset.plugin = '@dofe/dsh-yootun-daily-report'; style.textContent = `${css}${sourceStateCss}`; document.head.appendChild(style); return () => style.remove() }, 'dofe-yootun-daily-report: styles'); const t = ctx.locale.bind(NS); ctx.slots.inject('sidebar.footer.action', () => ctx.slots.register({ name: 'sidebar.footer.action', id: 'dofe-yootun-daily-report', order: 50, inject: () => ({ t }) }, Button)); ctx.slots.inject('shell.overlay', () => ctx.slots.register({ name: 'shell.overlay', id: 'dofe-yootun-daily-report', order: 50, inject: () => ({ t }) }, Overlay)) }
    module.exports = { apply, inject: ['slots', 'locale'] }

    return module.exports;
  },
});
