window.__ModuleLoader__.load({
  id: "@dofe/dsh-yootun-daily-report",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    const React = require('react')
    const { createElement: h, useEffect, useState, useSyncExternalStore } = React
    const { IconCloseOutline16, IconRefreshOutline16, IconDataOutline16, Tooltip } = require('@deepseek-ai/dsh-client-ui-primitives')
    const NS = 'dofe.yootun-daily-report'; const PATH = '/api/desktop/yootun/daily-report'
    const copy = { zh: { open: '昨日工作', title: '昨日工作日报', subtitle: '汇总本机 Agent 会话与工具调用', close: '关闭昨日工作日报', refresh: '刷新', sessions: '会话', turns: '轮次', completed: '完成', failed: '异常', tools: '工具调用', empty: '昨日没有可汇总的工作记录', unavailable: '本机事件暂不可用', privacy: '仅展示标题、工作区与聚合计数，不展示会话正文。', sources: '数据源状态', salesIntent: '销售意向', retrofit: '改装检索', knowledge: '企业知识' }, en: { open: 'Yesterday', title: 'Yesterday at a glance', subtitle: 'Local Agent sessions and tool calls', close: 'Close yesterday report', refresh: 'Refresh', sessions: 'Sessions', turns: 'Turns', completed: 'Completed', failed: 'Failed', tools: 'Tool calls', empty: 'No local work recorded yesterday', unavailable: 'Local events unavailable', privacy: 'Titles, workspaces, and aggregates only; conversation text is excluded.', sources: 'Source status', salesIntent: 'Sales intent', retrofit: 'Retrofit', knowledge: 'Knowledge' } }
    let opened = false; const listeners = new Set(); const emit = () => listeners.forEach(listener => listener()); const setOpened = value => { opened = value; emit() }; const subscribe = listener => { listeners.add(listener); return () => listeners.delete(listener) }; const snapshot = () => opened
    function Overlay({ t }) { const visible = useSyncExternalStore(subscribe, snapshot, snapshot); const [data, setData] = useState(null); const [revision, setRevision] = useState(0); useEffect(() => { if (!visible) return undefined; const controller = new AbortController(); void fetch(PATH, { credentials: 'same-origin', signal: controller.signal, headers: { Accept: 'application/json' } }).then(response => response.json()).then(setData).catch(() => setData({ activity: { status: 'unavailable' } })); return () => controller.abort() }, [visible, revision]); if (!visible) return null; const activity = data?.activity; const totals = activity?.totals || {}; const metrics = [['sessions', totals.sessions], ['turns', totals.turns], ['completed', totals.completed], ['failed', totals.failed], ['tools', totals.toolCalls]]; const sourceRows = [['salesIntent', data?.sources?.salesIntent], ['retrofit', data?.sources?.retrofit], ['knowledge', data?.sources?.knowledge]]; return h('div', { className: 'ydr-overlay' }, h('main', { className: 'ydr-shell' }, h('header', { className: 'ydr-header' }, h('div', null, h('h1', null, t('title')), h('p', null, t('subtitle'))), h('div', { className: 'ydr-actions' }, h(Tooltip, { label: t('refresh') }, h('button', { type: 'button', 'aria-label': t('refresh'), onClick: () => setRevision(value => value + 1) }, h(IconRefreshOutline16, { size: 16 }))), h(Tooltip, { label: t('close') }, h('button', { type: 'button', 'aria-label': t('close'), onClick: () => setOpened(false) }, h(IconCloseOutline16, { size: 16 }))))), h('div', { className: 'ydr-content' }, h('div', { className: 'ydr-metrics' }, ...metrics.map(([label, value]) => h('div', { className: 'ydr-metric', key: label }, h('span', null, t(label)), h('strong', null, String(value ?? 0)))), h('p', { className: 'ydr-privacy' }, t('privacy')), h('section', { className: 'ydr-sources' }, h('h2', null, t('sources')), ...sourceRows.map(([label, source]) => h('div', { className: 'ydr-source-row', key: label }, h('span', null, t(label)), h('b', { className: `ydr-source-${source?.status || 'unavailable'}` }, source?.status || 'unavailable')))), activity?.status === 'unavailable' ? h('div', { className: 'ydr-empty' }, t('unavailable')) : activity?.status === 'empty' ? h('div', { className: 'ydr-empty' }, t('empty')) : h('section', { className: 'ydr-section' }, (activity?.sessions || []).map(item => h('article', { className: 'ydr-row', key: `${item.workspace}-${item.title}` }, h('strong', null, item.title), h('span', null, `${item.workspace} · ${item.turns} ${t('turns')}`)))))) ) }
    function Button({ t }) { return h(Tooltip, { label: t('open') }, h('button', { type: 'button', className: 'ydr-button', 'aria-label': t('open'), onClick: () => setOpened(true) }, h(IconDataOutline16, { size: 18 }))) }
    const css = `.ydr-button{display:grid;width:36px;height:36px;place-items:center;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.ydr-button:hover{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}.ydr-overlay{position:fixed;inset:0;z-index:510;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary)}.ydr-shell{display:grid;grid-template-rows:auto 1fr;width:100%;height:100%;overflow:hidden}.ydr-header{display:flex;align-items:center;justify-content:space-between;padding:18px 24px;border-bottom:1px solid var(--dsw-alias-border-l1)}.ydr-header h1{margin:0;font-size:20px}.ydr-header p{margin:4px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px}.ydr-actions{display:flex;gap:6px}.ydr-actions button{display:grid;width:34px;height:34px;place-items:center;border:1px solid var(--dsw-alias-border-l1);border-radius:6px;background:var(--dsw-alias-bg-layer-1);color:inherit}.ydr-content{width:min(960px,100%);margin:0 auto;padding:28px 24px;overflow:auto}.ydr-metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));border-block:1px solid var(--dsw-alias-border-l1)}.ydr-metric{display:grid;gap:6px;padding:16px;border-right:1px solid var(--dsw-alias-border-l1)}.ydr-metric:last-child{border-right:0}.ydr-metric span{color:var(--dsw-alias-label-secondary);font-size:12px}.ydr-metric strong{font-size:24px}.ydr-privacy{color:var(--dsw-alias-label-secondary);font-size:12px}.ydr-sources{display:grid;gap:0;margin:20px 0}.ydr-sources h2{margin:0 0 8px;font-size:14px}.ydr-source-row{display:flex;justify-content:space-between;padding:10px 0;border-top:1px solid var(--dsw-alias-border-l1)}.ydr-source-ready{color:#188038}.ydr-source-unavailable{color:var(--dsw-alias-label-secondary)}.ydr-source-error{color:#c5221f}.ydr-section{display:grid;gap:0}.ydr-row{display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-top:1px solid var(--dsw-alias-border-l1)}.ydr-row span{color:var(--dsw-alias-label-secondary);font-size:12px}.ydr-empty{display:grid;min-height:180px;place-items:center;color:var(--dsw-alias-label-secondary)}@media(max-width:700px){.ydr-header,.ydr-content{padding-left:16px;padding-right:16px}.ydr-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.ydr-metric:nth-child(2n){border-right:0}.ydr-metric:last-child{grid-column:span 2;border-top:1px solid var(--dsw-alias-border-l1)}.ydr-row{align-items:flex-start;flex-direction:column}}`
    function apply(ctx) { ctx.effect(() => ctx.locale.register(NS, copy), 'dofe-yootun-daily-report: dictionaries'); ctx.effect(() => { const style = document.createElement('style'); style.dataset.plugin = '@dofe/dsh-yootun-daily-report'; style.textContent = css; document.head.appendChild(style); return () => style.remove() }, 'dofe-yootun-daily-report: styles'); const t = ctx.locale.bind(NS); ctx.slots.inject('sidebar.footer.action', () => ctx.slots.register({ name: 'sidebar.footer.action', id: 'dofe-yootun-daily-report', order: 50, inject: () => ({ t }) }, Button)); ctx.slots.inject('shell.overlay', () => ctx.slots.register({ name: 'shell.overlay', id: 'dofe-yootun-daily-report', order: 50, inject: () => ({ t }) }, Overlay)) }
    module.exports = { apply, inject: ['slots', 'locale'] }

    return module.exports;
  },
});
