const React = require('react')
const { createElement: h, useState, useSyncExternalStore } = React
const { IconCloseOutline16, IconSearchOutline16, Tooltip } = require('@deepseek-ai/dsh-client-ui-primitives')
const NS = 'dofe.yootun-retrofit'; const PATH = '/api/desktop/yootun/retrofit'
const copy = { zh: { open: '改装检索', title: '车辆改装检索', subtitle: '只读查询改装方案与配件信息', close: '关闭改装检索', search: '查询', placeholder: '例如：2024 款车型的灯光升级方案', empty: '输入需求后开始查询', unavailable: '改装工具暂不可用', error: '查询失败', privacy: '结果仅供方案筛选，执行改装前需人工确认。' }, en: { open: 'Retrofit search', title: 'Vehicle retrofit search', subtitle: 'Read-only retrofit plans and parts discovery', close: 'Close retrofit search', search: 'Search', placeholder: 'e.g. lighting upgrade for a 2024 model', empty: 'Enter a requirement to search', unavailable: 'Retrofit tool unavailable', error: 'Search failed', privacy: 'Results are for discovery only; confirm before any work.' } }
let opened = false; const listeners = new Set(); const emit = () => listeners.forEach(listener => listener()); const setOpened = value => { opened = value; emit() }; const subscribe = listener => { listeners.add(listener); return () => listeners.delete(listener) }; const snapshot = () => opened
function Overlay({ t }) { const visible = useSyncExternalStore(subscribe, snapshot, snapshot); const [query, setQuery] = useState(''); const [data, setData] = useState(null); const [busy, setBusy] = useState(false); if (!visible) return null; const run = async () => { if (!query.trim()) return; setBusy(true); try { const response = await fetch(PATH, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ query }) }); setData(await response.json()) } catch { setData({ status: 'error' }) } finally { setBusy(false) } }; return h('div', { className: 'yr-overlay' }, h('main', { className: 'yr-shell' }, h('header', { className: 'yr-header' }, h('div', null, h('h1', null, t('title')), h('p', null, t('subtitle'))), h(Tooltip, { label: t('close') }, h('button', { type: 'button', 'aria-label': t('close'), onClick: () => setOpened(false) }, h(IconCloseOutline16, { size: 16 })))), h('div', { className: 'yr-content' }, h('div', { className: 'yr-search' }, h('input', { value: query, maxLength: 500, placeholder: t('placeholder'), onChange: event => setQuery(event.target.value), onKeyDown: event => { if (event.key === 'Enter') run() } }), h('button', { type: 'button', onClick: run, disabled: busy || !query.trim() }, h(IconSearchOutline16, { size: 16 }), busy ? '…' : t('search'))), h('p', { className: 'yr-privacy' }, t('privacy')), h('section', { className: 'yr-result' }, !data ? t('empty') : data.status === 'unavailable' ? t('unavailable') : data.status === 'error' ? t('error') : h('pre', null, JSON.stringify(data.result, null, 2)))))) }
function Button({ t }) { return h(Tooltip, { label: t('open') }, h('button', { type: 'button', className: 'yr-button', 'aria-label': t('open'), onClick: () => setOpened(true) }, h(IconSearchOutline16, { size: 18 }))) }
const css = `.yr-button{display:grid;width:36px;height:36px;place-items:center;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.yr-button:hover{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}.yr-overlay{position:fixed;inset:0;z-index:510;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary)}.yr-shell{display:grid;grid-template-rows:auto 1fr;width:100%;height:100%;overflow:hidden}.yr-header{display:flex;align-items:center;justify-content:space-between;padding:18px 24px;border-bottom:1px solid var(--dsw-alias-border-l1)}.yr-header h1{margin:0;font-size:20px}.yr-header p{margin:4px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px}.yr-header button{display:grid;width:34px;height:34px;place-items:center;border:1px solid var(--dsw-alias-border-l1);border-radius:6px;background:var(--dsw-alias-bg-layer-1);color:inherit}.yr-content{width:min(900px,100%);margin:0 auto;padding:28px 24px;overflow:auto}.yr-search{display:flex;gap:8px}.yr-search input{flex:1;min-width:0;padding:10px 12px;border:1px solid var(--dsw-alias-border-l1);border-radius:6px;background:var(--dsw-alias-bg-layer-1);color:inherit;font:inherit}.yr-search button{display:inline-flex;align-items:center;gap:6px;padding:0 14px;border:0;border-radius:6px;background:var(--dsw-alias-control-fill-brand);color:white;font:inherit}.yr-search button:disabled{opacity:.5}.yr-privacy{color:var(--dsw-alias-label-secondary);font-size:12px}.yr-result{min-height:220px;margin-top:20px;padding:18px;border-top:1px solid var(--dsw-alias-border-l1);white-space:pre-wrap;color:var(--dsw-alias-label-secondary)}.yr-result pre{margin:0;color:var(--dsw-alias-label-primary);white-space:pre-wrap}@media(max-width:600px){.yr-header,.yr-content{padding-left:16px;padding-right:16px}.yr-search{flex-direction:column}.yr-search button{min-height:36px;justify-content:center}}`
function apply(ctx) { ctx.effect(() => ctx.locale.register(NS, copy), 'dofe-yootun-retrofit: dictionaries'); ctx.effect(() => { const style = document.createElement('style'); style.dataset.plugin = '@dofe/dsh-yootun-retrofit'; style.textContent = css; document.head.appendChild(style); return () => style.remove() }, 'dofe-yootun-retrofit: styles'); const t = ctx.locale.bind(NS); ctx.slots.inject('sidebar.footer.action', () => ctx.slots.register({ name: 'sidebar.footer.action', id: 'dofe-yootun-retrofit', order: 45, inject: () => ({ t }) }, Button)); ctx.slots.inject('shell.overlay', () => ctx.slots.register({ name: 'shell.overlay', id: 'dofe-yootun-retrofit', order: 45, inject: () => ({ t }) }, Overlay)) }
module.exports = { apply, inject: ['slots', 'locale'] }
