window.__ModuleLoader__.load({
  id: "@dofe/dsh-yootun-finops",
  factory: (require) => { var module = { exports: {} }; var exports = module.exports;
    const React = require('react')
    const { createElement: h, useEffect, useState, useSyncExternalStore } = React
    const { IconCloseOutline16, IconDataOutline16, IconRefreshOutline16, IconWarningOutline16, Tooltip } = require('@deepseek-ai/dsh-client-ui-primitives')
    const NS = 'dofe.yootun-finops'; const PATH = '/api/desktop/yootun/finops'
    const copy = { zh: { open: '模型与预算', title: '模型与预算治理', subtitle: '消费、预算与异常告警', close: '关闭模型与预算', refresh: '刷新', spend: '昨日消费', budget: '月度预算', remaining: '预算剩余', alerts: '异常告警', models: '模型构成', empty: '暂无预算或告警', source: '来源' }, en: { open: 'Model & budget', title: 'Model & budget governance', subtitle: 'Spend, budgets, and anomaly alerts', close: 'Close model & budget', refresh: 'Refresh', spend: 'Yesterday spend', budget: 'Monthly budget', remaining: 'Budget remaining', alerts: 'Alerts', models: 'Model mix', empty: 'No budget or alerts yet', source: 'Source' } }
    let opened = false; const listeners = new Set(); const emit = () => listeners.forEach(listener => listener()); const setOpened = value => { opened = value; emit() }; const subscribe = listener => { listeners.add(listener); return () => listeners.delete(listener) }; const snapshot = () => opened
    async function load(signal) { const response = await fetch(PATH, { credentials: 'same-origin', signal, headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('finops request failed'); return response.json() }
    function Metric({ label, value }) { return h('div', { className: 'yf-metric' }, h('span', null, label), h('strong', null, value ?? '-')) }
    function Overlay({ t }) { const visible = useSyncExternalStore(subscribe, snapshot, snapshot); const [data, setData] = useState(null); const [error, setError] = useState(false); const [revision, setRevision] = useState(0); useEffect(() => { if (!visible) return undefined; const controller = new AbortController(); setError(false); void load(controller.signal).then(setData).catch(cause => { if (cause?.name !== 'AbortError') setError(true) }); return () => controller.abort() }, [visible, revision]); useEffect(() => { if (!visible) return undefined; const key = event => { if (event.key === 'Escape') setOpened(false) }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [visible]); if (!visible) return null; const current = data || { summary: {}, budgets: [], alerts: [], models: [] }; const body = error && !data ? h('div', { role: 'alert', className: 'yf-empty' }, 'Unable to load finops') : h(React.Fragment, null, h('div', { className: 'yf-metrics' }, h(Metric, { label: t('spend'), value: current.summary.spend ?? '不可用' }), h(Metric, { label: t('budget'), value: current.summary.budget ?? '未配置' }), h(Metric, { label: t('remaining'), value: current.summary.remaining ?? '不可用' }), h(Metric, { label: t('alerts'), value: current.summary.alerts ?? 0 })), h('section', { className: 'yf-section' }, h('h2', null, t('models')), current.models?.length ? current.models.map(item => h('article', { className: 'yf-row', key: item.id }, h('strong', null, item.name), h('span', null, `${item.requests} requests · ${item.tokens} tokens · ${item.cost}`))) : h('div', { className: 'yf-empty' }, t('empty'))), h('section', { className: 'yf-section' }, h('h2', null, t('alerts')), current.alerts?.map(item => h('article', { className: 'yf-row', key: item.id }, h(IconWarningOutline16, { size: 14 }), h('span', null, `${item.title} · ${item.status}`))))); return h('div', { className: 'yf-overlay' }, h('main', { className: 'yf-shell', 'aria-labelledby': 'yf-title' }, h('header', { className: 'yf-header' }, h('div', null, h('h1', { id: 'yf-title' }, t('title')), h('p', null, t('subtitle'))), h('div', { className: 'yf-header-buttons' }, h(Tooltip, { label: t('refresh') }, h('button', { type: 'button', 'aria-label': t('refresh'), onClick: () => setRevision(value => value + 1) }, h(IconRefreshOutline16, { size: 16 }))), h(Tooltip, { label: t('close') }, h('button', { type: 'button', 'aria-label': t('close'), onClick: () => setOpened(false) }, h(IconCloseOutline16, { size: 16 }))))), h('div', { className: 'yf-content' }, body))) }
    function Button({ wide, t }) { return h(Tooltip, { label: t('open'), disabled: wide }, h('button', { type: 'button', className: `yf-button${wide ? ' yf-wide' : ''}`, 'aria-label': t('open'), onClick: () => setOpened(true) }, h(IconDataOutline16, { size: wide ? 14 : 18 }), wide ? h('span', null, t('open')) : null)) }
    const css = `.yf-button{display:flex;width:36px;height:36px;align-items:center;justify-content:center;gap:8px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.yf-button:hover{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}.yf-wide{width:100%;height:34px;justify-content:flex-start;padding:0 10px}.yf-wide span{font-size:13px}.yf-overlay{position:fixed;inset:0;z-index:510;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary)}.yf-shell{display:grid;grid-template-rows:auto 1fr;width:100%;height:100%;overflow:hidden}.yf-header{display:flex;min-height:74px;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid var(--dsw-alias-border-l1)}.yf-header h1{margin:0;font-size:20px}.yf-header p{margin:4px 0 0;color:var(--dsw-alias-label-secondary);font-size:13px}.yf-header-buttons{display:flex;gap:6px}.yf-header-buttons button{display:grid;width:34px;height:34px;place-items:center;border:1px solid var(--dsw-alias-border-l1);border-radius:6px;background:var(--dsw-alias-bg-layer-1);color:inherit;cursor:pointer}.yf-content{overflow:auto;padding:22px 24px 40px}.yf-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));max-width:1120px;margin:0 auto;border-block:1px solid var(--dsw-alias-border-l1)}.yf-metric{display:grid;min-height:82px;align-content:center;gap:6px;padding:12px 16px;border-right:1px solid var(--dsw-alias-border-l1)}.yf-metric:last-child{border-right:0}.yf-metric span,.yf-row span{color:var(--dsw-alias-label-secondary);font-size:12px}.yf-metric strong{font-size:20px}.yf-section{display:grid;gap:10px;max-width:1120px;margin:24px auto 0}.yf-section h2{margin:0;font-size:14px}.yf-row{display:flex;align-items:center;gap:10px;padding:14px 16px;border-top:1px solid var(--dsw-alias-border-l1)}.yf-row strong{min-width:130px}.yf-empty{display:grid;min-height:150px;place-items:center;color:var(--dsw-alias-label-secondary);font-size:13px;text-align:center}@media(max-width:800px){.yf-header,.yf-content{padding-left:16px;padding-right:16px}.yf-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.yf-metric:nth-child(2){border-right:0}.yf-metric:nth-child(-n+2){border-bottom:1px solid var(--dsw-alias-border-l1)}.yf-row{align-items:flex-start;flex-direction:column}.yf-row strong{min-width:0}}`
    function apply(ctx) { ctx.effect(() => ctx.locale.register(NS, copy), 'dofe-yootun-finops: dictionaries'); ctx.effect(() => { const style = document.createElement('style'); style.dataset.plugin = '@dofe/dsh-yootun-finops'; style.textContent = css; document.head.appendChild(style); return () => style.remove() }, 'dofe-yootun-finops: styles'); const t = ctx.locale.bind(NS); ctx.slots.inject('sidebar.footer.action', () => ctx.slots.register({ name: 'sidebar.footer.action', id: 'dofe-yootun-finops', order: 55, inject: () => ({ t }) }, Button)); ctx.slots.inject('shell.overlay', () => ctx.slots.register({ name: 'shell.overlay', id: 'dofe-yootun-finops', order: 55, inject: () => ({ t }) }, Overlay)) }
    module.exports = { apply, inject: ['slots', 'locale'] }
    
    exports.apply = apply; exports.inject = ['slots', 'locale']; return module.exports; },
});
